export const ARRAY_TITLE_TABLE_1 = [
  'CURP',
  'Nombre',
  'Apellido Paterno',
  'Apellido Materno',
  'Fecha Nacimiento:',
  'Fecha de Inicio de operaciones:',
  'Situaci├│n del contribuyente:',
  'ACTIVO',
  'Fecha del ├║ltimo cambio de situaci├│n:',
  '21-08-2018',
]

export const ARRAY_INITIAL_DATACLIENT_SCRAPING: DataClientScraping = {
  'Apellido Materno': '',
  'Apellido Paterno': '',
  Colonia: '',
  'Entidad Federativa': '',
  'Fecha Nacimiento': '',
  'Municipio o delegación': '',
  'Nombre de la Entidad Federativa': '',
  'Nombre de la vialidad': '',
  'Número exterior': '',
  'Tipo de vialidad': '',
  CP: '',
  CURP: '',
  idCIF: '',
  Nombre: '',
  RFC: '',
  'Correo electrónico': '',
  'Fecha de Inicio de operaciones': '',
  'Fecha del último cambio de situación:': '',
  'Número interior': '',
  'Situación del contribuyente': '',
  Régimen: [],
}
