image: atlassian/default-image:4

clone:
  depth: full

options:
  docker: true
  size: 2x

pipelines:
  tags:
    test-*:
      - step:
          name: Build Docker image on release
          deployment: test
          script:
            - echo GRAPHQL_URL="${GRAPHQL_URL}"  > .env
            - echo NEXTAUTH_URL="${NEXTAUTH_URL}" >> .env
            - echo NEXTAUTH_SECRET="${NEXTAUTH_SECRET}" >> .env
            - echo NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME="${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}" >> .env
            - echo CLOUDINARY_API_KEY="${CLOUDINARY_API_KEY}" >> .env
            - echo CLOUDINARY_API_SECRET="${CLOUDINARY_API_SECRET}">> .env
            - echo CLOUDINARY_FOLDER="${CLOUDINARY_FOLDER}">> .env
            - echo DATABASE_URL="${DATABASE_URL}" >> .env
            - echo DB_DATABASE_NAME="${DB_DATABASE_NAME}" >> .env
            - echo DB_USERNAME="${DB_USERNAME}" >> .env
            - echo DB_PASSWORD="${DB_PASSWORD}" >> .env
            - echo CLIENT_ID="${CLIENT_ID}" >> .env
            - echo CLIENT_SECRET="${CLIENT_SECRET}" >> .env
            - echo CLIENT_SCOPE="${CLIENT_SCOPE}" >> .env
            - echo GITHUB_ID="${GITHUB_ID}" >> .env
            - echo GITHUB_SECRET= "${GITHUB_SECRET}" >> .env
            - echo EXTERNAL_API_JWT_PRIVATE_KEY= "${EXTERNAL_API_JWT_PRIVATE_KEY}" >> .env
            - echo EXTERNAL_API_JWT_PUBLIC_KEY= "${EXTERNAL_API_JWT_PUBLIC_KEY}" >> .env
            - echo NEXT_PUBLIC_GRAPHQL_URL= "${NEXT_PUBLIC_GRAPHQL_URL}" >> .env
            - echo NEXT_PUBLIC_GRAPHQL_PUBLIC_URL= "${NEXT_PUBLIC_GRAPHQL_PUBLIC_URL}" >> .env
            - echo .env
            - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            - docker build -t afllopez/uber:${BITBUCKET_TAG} --build-arg RELEASE_VERSION=$BITBUCKET_TAG .
            - docker push afllopez/uber:${BITBUCKET_TAG}
          services:
            - docker
      - step:
          name: Deploy Test
          script:
            - sed -i "s|{{image}}|afllopez/uber:$BITBUCKET_TAG|g" .kube/default/base/uber-deployment.yaml
            - pipe: atlassian/kubectl-run:3.8.0
              variables:
                KUBE_CONFIG: $KUBECONFIG
                KUBECTL_COMMAND: 'apply'
                RESOURCE_PATH: '.kube/default/testing/'
                KUBECTL_APPLY_ARGS: '-k'
                KUBECTL_ARGS:
                  - '--context=default'
    dev-*:
      - step:
          name: Build Docker image on release
          deployment: dev
          script:
            - echo GRAPHQL_URL="${GRAPHQL_URL}"  > .env
            - echo NEXTAUTH_URL="${NEXTAUTH_URL}" >> .env
            - echo NEXTAUTH_SECRET="${NEXTAUTH_SECRET}" >> .env
            - echo NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME="${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}" >> .env
            - echo CLOUDINARY_API_KEY="${CLOUDINARY_API_KEY}" >> .env
            - echo CLOUDINARY_API_SECRET="${CLOUDINARY_API_SECRET}">> .env
            - echo CLOUDINARY_FOLDER="${CLOUDINARY_FOLDER}">> .env
            - echo DATABASE_URL="${DATABASE_URL}" >> .env
            - echo DB_DATABASE_NAME="${DB_DATABASE_NAME}" >> .env
            - echo DB_USERNAME="${DB_USERNAME}" >> .env
            - echo DB_PASSWORD="${DB_PASSWORD}" >> .env
            - echo CLIENT_ID="${CLIENT_ID}" >> .env
            - echo CLIENT_SECRET="${CLIENT_SECRET}" >> .env
            - echo CLIENT_SCOPE="${CLIENT_SCOPE}" >> .env
            - echo GITHUB_ID="${GITHUB_ID}" >> .env
            - echo GITHUB_SECRET= "${GITHUB_SECRET}" >> .env
            - echo EXTERNAL_API_JWT_PRIVATE_KEY= "${EXTERNAL_API_JWT_PRIVATE_KEY}" >> .env
            - echo EXTERNAL_API_JWT_PUBLIC_KEY= "${EXTERNAL_API_JWT_PUBLIC_KEY}" >> .env
            - echo NEXT_PUBLIC_GRAPHQL_URL= "${NEXT_PUBLIC_GRAPHQL_URL}" >> .env
            - echo NEXT_PUBLIC_GRAPHQL_PUBLIC_URL= "${NEXT_PUBLIC_GRAPHQL_PUBLIC_URL}" >> .env
            - echo .env
            - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            - docker build -t afllopez/uber:${BITBUCKET_TAG} --build-arg RELEASE_VERSION=$BITBUCKET_TAG .
            - docker push afllopez/uber:${BITBUCKET_TAG}
          services:
            - docker
      - step:
          name: Deploy Dev
          script:
            - sed -i "s|{{image}}|afllopez/uber:$BITBUCKET_TAG|g" .kube/default/base/uber-deployment.yaml
            - pipe: atlassian/kubectl-run:3.8.0
              variables:
                KUBE_CONFIG: $KUBECONFIG
                KUBECTL_COMMAND: 'apply'
                RESOURCE_PATH: '.kube/default/dev/'
                KUBECTL_APPLY_ARGS: '-k'
                KUBECTL_ARGS:
                  - '--context=default'
    prod-*:
      - step:
          name: Build Docker image on release
          deployment: Production
          script:
            - echo GRAPHQL_URL="${GRAPHQL_URL}"  > .env
            - echo NEXTAUTH_URL="${NEXTAUTH_URL}" >> .env
            - echo NEXTAUTH_SECRET="${NEXTAUTH_SECRET}" >> .env
            - echo NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME="${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}" >> .env
            - echo CLOUDINARY_API_KEY="${CLOUDINARY_API_KEY}" >> .env
            - echo CLOUDINARY_API_SECRET="${CLOUDINARY_API_SECRET}">> .env
            - echo CLOUDINARY_FOLDER="${CLOUDINARY_FOLDER}">> .env
            - echo DATABASE_URL="${DATABASE_URL}" >> .env
            - echo DB_DATABASE_NAME="${DB_DATABASE_NAME}" >> .env
            - echo DB_USERNAME="${DB_USERNAME}" >> .env
            - echo DB_PASSWORD="${DB_PASSWORD}" >> .env
            - echo CLIENT_ID="${CLIENT_ID}" >> .env
            - echo CLIENT_SECRET="${CLIENT_SECRET}" >> .env
            - echo CLIENT_SCOPE="${CLIENT_SCOPE}" >> .env
            - echo GITHUB_ID="${GITHUB_ID}" >> .env
            - echo GITHUB_SECRET= "${GITHUB_SECRET}" >> .env
            - echo EXTERNAL_API_JWT_PRIVATE_KEY= "${EXTERNAL_API_JWT_PRIVATE_KEY}" >> .env
            - echo EXTERNAL_API_JWT_PUBLIC_KEY= "${EXTERNAL_API_JWT_PUBLIC_KEY}" >> .env
            - echo NEXT_PUBLIC_GRAPHQL_URL= "${NEXT_PUBLIC_GRAPHQL_URL}" >> .env
            - echo NEXT_PUBLIC_GRAPHQL_PUBLIC_URL= "${NEXT_PUBLIC_GRAPHQL_PUBLIC_URL}" >> .env

            - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            - docker build -t afllopez/uber:${BITBUCKET_TAG} --build-arg RELEASE_VERSION=$BITBUCKET_TAG .
            - docker push afllopez/uber:${BITBUCKET_TAG}
          services:
            - docker
      - step:
          name: Deploy Production
          script:
            - sed -i "s|{{image}}|afllopez/uber:$BITBUCKET_TAG|g" .kube/default/base_prod/web-autofinrent-deployment.yaml
            - pipe: atlassian/kubectl-run:3.8.0
              variables:
                KUBE_CONFIG: $KUBECONFIG_PROD
                KUBECTL_COMMAND: 'apply'
                RESOURCE_PATH: '.kube/default/prod/'
                KUBECTL_APPLY_ARGS: '-k'
                KUBECTL_ARGS:
                  - '--context=default'
definitions:
  services:
    docker:
      memory: 4096
