version: '3.8'
services:
  postgres:
    container_name: uber_db
    image: postgres:latest
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5435:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
