
-- 2025-02-06 21:01:14.2830
INSERT INTO "public"."Product" ("id", "title", "brand", "model", "year", "series", "picture", "defaultWeeklyPrice", "defaultLeasingPeriod", "createdAt", "idversion", "updatedAt") VALUES ('251d198c-3769-4c7c-a4de-66186f124167', 'V-Drive Base', 'NISSAN', 'V-DRIVE', 2024, 'TM', 'https://www.autofinrent.com/images/cars/VDRIVE_3.png', 3100, 40, '2025-01-22 16:54:45.902', 40786, '2025-01-22 16:54:45.902');
INSERT INTO "public"."Product" ("id", "title", "brand", "model", "year", "series", "picture", "defaultWeeklyPrice", "defaultLeasingPeriod", "createdAt", "estimatedAcceleration", "engineType", "estimatedHorsepower", "estimatedTopSpeedKmH", "numberOfSpeeds", "turbo", "cylinders", "fuelType", "liters", "estimatedTorqueLbFt", "startStop", "frontElectricWindows", "transmission", "idversion", "updatedAt") VALUES ('9fdef98a-6994-4c49-bc44-445cfdabc30c', 'Chevrolet Aveo 2024', 'CHEVROLET', 'AVEO', 2024, 'LS', 'https://web.test.divisionautomotriz.com//images/cars/Aveo.jpg', 1500, 12, '2024-07-18 21:17:18.811', 11, 'Combustión', 107, 170, 5, 'No', '4L', 'Gasolina', 1.5, 104, 'No', 'Sí', 'Manual', 40579, '2024-07-18 21:17:18.811');
INSERT INTO "public"."Product" ("id", "title", "brand", "model", "year", "series", "picture", "defaultWeeklyPrice", "defaultLeasingPeriod", "createdAt", "idversion", "updatedAt") VALUES ('b1bdbcdd-4f81-413d-a9cb-24f4eca2659a', 'Versa Sense TM', 'NISSAN', 'VERSA', 2025, 'Base', 'https://www.autofinrent.com/images/cars/VERSA_2.png', 3314, 40, '2025-01-22 16:54:45.902', 40787, '2025-01-22 16:54:45.902');

-- 2025-02-06 21:01:28.7340
UPDATE "public"."Product" SET "isActive" = 't' WHERE "id" = 'b1bdbcdd-4f81-413d-a9cb-24f4eca2659a';
UPDATE "public"."Product" SET "isActive" = 't' WHERE "id" = '9fdef98a-6994-4c49-bc44-445cfdabc30c';
UPDATE "public"."Product" SET "isActive" = 't' WHERE "id" = '251d198c-3769-4c7c-a4de-66186f124167';

-- 2025-02-06 21:02:05.3430
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('APPLICATION_BACKOFFICE_APPROVAL', 'Aprobación de cliente');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('APPLICATION_MANAGER_APPROVAL', 'Aprobación del coordinador');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('DELIVERY_DATE', 'Agenda Entrega');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_ADDRESS_INPUT', 'Registro de Domicilio');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_ADDRESS_PROOF_JOB', 'Procesando Comprobante de Domicilio');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_ADDRESS_PROOF_UPLOAD', 'Carga de Comprobante de Domicilio');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_ADDRESS_VERIFICATION', 'Verificación de domicilio');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_DRIVERS_LICENSE_JOB', 'Procesando Licencia de Conducir');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_DRIVERS_LICENSE_UPLOAD', 'Carga de Licencia de Conducir');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_DRIVERS_LICENSE_VERIFICATION', 'Verificación de Licencia de Conducir');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_FINAL_APPROVAL', 'Aprobación de Arrendamiento');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_IDENTIFICATION_CARD_JOB', 'Procesando Identificación Oficial');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_IDENTIFICATION_CARD_UPLOAD', 'Carga de Identificación Oficial');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_IDENTIFICATION_CARD_VERIFICATION', 'Verificación de Identificación Oficial');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_INACTIVITY_STATEMENT_INPUT', 'Motivo de inactividad');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_INACTIVITY_STATEMENT_JOB', 'Proceso de carga de certificado de inactividad');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_INACTIVITY_STATEMENT_UPLOAD', 'Carga de certificado de inactividad');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_INACTIVITY_STATEMENT_VERIFICATION', 'Verificación de certificado de inactividad');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_INCOME_STATEMENT_JOB', 'Procesando Otros ingresos');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_INCOME_STATEMENT_UPLOAD', 'Carga de Otros ingresos');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_INCOME_STATEMENT_VERIFICATION', 'Verificación de Otros ingresos');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_MEET_ADDRESS_MATCH', 'Validar de domicilio en entrevista');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_MEET_CANCEL_DATE', 'Cancelar entrevista');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_MEET_CHECKIN', 'Validación de identidad ');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_MEET_CONFIRM_DATE', 'Confirmación de fecha para entrevista');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_MEET_GUEST_INVITATION', 'Inició  cliente llamada');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_MEET_HOST_INVITATION', 'Ingresar a la sala');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_MEET_PICK_DATE', 'Agenda de entrevista');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_MEET_RESCHEDULE', 'Reagendar fecha de entrevista');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_SELFIE_PICTURE_JOB', 'Procesando Foto de Perfil');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_SELFIE_PICTURE_UPLOAD', 'Carga de Foto de Perfil');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_SELFIE_PICTURE_VERIFICATION', 'Verificación de Foto de Perfil');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_TAX_IDENTIFICATION_JOB', 'Procesando Constancia de Situación Fiscal');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_TAX_IDENTIFICATION_UPLOAD', 'Carga de Constancia de Situación Fiscal');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('KYC_TAX_IDENTIFICATION_VERIFICATION', 'Verificación de Constancia de Situación Fiscal');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('LEASING_CONTRACT_SIGNATURE', 'Firma de contrato');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('PAYMENT_CHECKOUT', 'Pago en Ventanilla');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('PAYMENT_RECONCILIATION', 'Conciliación de pago');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('PAYMENT_VALIDATION', 'Pago Inicial Realizado');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('PENDING_DOCUMENTS', 'Documentos de Vehículo');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('UBER_DRIVER_CONTRACT', 'Asociar vehículo al conductor App UBER');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('UBER_VEHICLE_REGISTRATION', 'Alta de Vehículo App UBER ');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('VEHICLE_ASSURANCE', 'Póliza de seguro');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('VEHICLE_AUTHORIZATION', 'Tarjeta de circulación');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('VEHICLE_HANDOFF_CANCEL_DATE', 'Cancelar fecha de entrega');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('VEHICLE_HANDOFF_CHECKIN', 'Check de entrega');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('VEHICLE_HANDOFF_CONFIRM_DATE', 'Confirmar fecha de entrega');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('VEHICLE_HANDOFF_PICK_DATE', 'Agendar fecha de entrega');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('VEHICLE_INVENTORY_RELEASE', 'Cancelar reserva de vehículo');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('VEHICLE_INVENTORY_RESERVE', 'Reserva de vehículo');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('VEHICLE_STREET_TAG_INSTALLATION', 'TAG');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('VEHICLE_TITLE', 'Factura');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('VEHICLE_TRACKER_INSTALLATION', 'Instalación de dispositivo de rastreo');
INSERT INTO "public"."TaskType" ("id", "name") VALUES ('VEHICLE_TRACKER_SIM', 'Configuración SIM');

-- 2025-02-06 21:02:39.1130
INSERT INTO "public"."ProspectStatus" ("id", "name", "manualAssignable") VALUES ('APPLICATION_AWAITING_ACCOUNT_AND_PAYMENT', 'Pago y Cuenta', 'false');
INSERT INTO "public"."ProspectStatus" ("id", "name", "manualAssignable") VALUES ('APPLICATION_AWAITING_HANDOFF', 'Por Entregar', 'false');
INSERT INTO "public"."ProspectStatus" ("id", "name", "manualAssignable") VALUES ('APPLICATION_AWAITING_PREAPPROVAL', 'Solicitud esperando preaprobación', 'false');
INSERT INTO "public"."ProspectStatus" ("id", "name", "manualAssignable") VALUES ('APPLICATION_AWAITING_VEHICLE', 'Preparando unidad', 'false');
INSERT INTO "public"."ProspectStatus" ("id", "name", "manualAssignable") VALUES ('APPLICATION_CANCELED_BY_USER', 'Solicitud cancelada por usuario', 'false');
INSERT INTO "public"."ProspectStatus" ("id", "name", "manualAssignable") VALUES ('APPLICATION_EXPIRED', 'Solicitud expirada', 'false');
INSERT INTO "public"."ProspectStatus" ("id", "name", "manualAssignable") VALUES ('APPLICATION_KYC_AWAITING_DOCUMENTATION', 'Documentación', 'false');
INSERT INTO "public"."ProspectStatus" ("id", "name", "manualAssignable") VALUES ('APPLICATION_KYC_AWAITING_MEET', 'Videollamada', 'false');
INSERT INTO "public"."ProspectStatus" ("id", "name", "manualAssignable") VALUES ('APPLICATION_REJECTED', 'Solicitud rechazada', 'false');
INSERT INTO "public"."ProspectStatus" ("id", "name", "manualAssignable") VALUES ('CUSTOMER_INTERESTED', 'Si quiero', 'true');
INSERT INTO "public"."ProspectStatus" ("id", "name", "manualAssignable") VALUES ('CUSTOMER_NOT_ANSWERING', 'No contesta', 'true');
INSERT INTO "public"."ProspectStatus" ("id", "name", "manualAssignable") VALUES ('CUSTOMER_NOT_INTERESTED', 'No me interesa', 'true');
INSERT INTO "public"."ProspectStatus" ("id", "name", "manualAssignable") VALUES ('CUSTOMER_UNDER_REVISION', 'En revisión', 'true');
INSERT INTO "public"."ProspectStatus" ("id", "name", "manualAssignable") VALUES ('PROSPECT_CLOSED', 'Prospecto cerrado', 'false');
INSERT INTO "public"."ProspectStatus" ("id", "name", "manualAssignable") VALUES ('PROSPECT_CREATED', 'Por contactar', 'true');

-- 2025-02-06 21:02:51.2550
INSERT INTO "public"."ProspectActivityType" ("id", "name") VALUES ('APPLICATION_CREATED', 'Solicitud creada');
INSERT INTO "public"."ProspectActivityType" ("id", "name") VALUES ('APPLICATION_EXPIRED', 'Solicitud expirada');
INSERT INTO "public"."ProspectActivityType" ("id", "name") VALUES ('APPLICATION_KYC_APPROVED', 'KYC Aprobado');
INSERT INTO "public"."ProspectActivityType" ("id", "name") VALUES ('APPLICATION_KYC_USER_LOGGED_IN_APP', 'Usuario inició onboard en la APP');
INSERT INTO "public"."ProspectActivityType" ("id", "name") VALUES ('APPLICATION_PREAPPROVAL_ACCEPTED', 'Solicitud preaprobada');
INSERT INTO "public"."ProspectActivityType" ("id", "name") VALUES ('APPLICATION_PREAPPROVAL_REQUESTED', 'Solicitando preaprobación de solicitud');
INSERT INTO "public"."ProspectActivityType" ("id", "name") VALUES ('APPLICATION_REJECTED', 'Solicitud rechazada');
INSERT INTO "public"."ProspectActivityType" ("id", "name") VALUES ('CUSTOMER_SUPPORT_CLOSED', 'Sesión de soporte cerrada');
INSERT INTO "public"."ProspectActivityType" ("id", "name") VALUES ('CUSTOMER_SUPPORT_CONTACTED_USER', 'Soporte contactó a usuario');
INSERT INTO "public"."ProspectActivityType" ("id", "name") VALUES ('NOTE', 'Nota');
INSERT INTO "public"."ProspectActivityType" ("id", "name") VALUES ('PROSPECT_ABANDONED', 'Prospecto abandona');
INSERT INTO "public"."ProspectActivityType" ("id", "name") VALUES ('PROSPECT_CONVERTED', 'Prospecto convertido');
INSERT INTO "public"."ProspectActivityType" ("id", "name") VALUES ('PROSPECT_CREATED', 'Prospecto creado');
INSERT INTO "public"."ProspectActivityType" ("id", "name") VALUES ('PROSPECT_REJECTED', 'Prospecto rechazado');
INSERT INTO "public"."ProspectActivityType" ("id", "name") VALUES ('PROSPECT_STATUS_UPDATED', 'Actualización de estado de prospecto');
INSERT INTO "public"."ProspectActivityType" ("id", "name") VALUES ('PROSPECT_SUPPORT_USER_ASSIGNED', 'Ejecutivo asignado');
INSERT INTO "public"."ProspectActivityType" ("id", "name") VALUES ('QUOTE_CREATED', 'Nueva oferta');
INSERT INTO "public"."ProspectActivityType" ("id", "name") VALUES ('USER_CONTACTED_CUSTOMER_SUPPORT', 'Usuario contactó a soporte');

-- 2025-02-06 21:03:07.2450
INSERT INTO "public"."Promotion" ("id", "name", "isActive", "createdAt", "updatedAt") VALUES ('PROMO1', 'Promoción 1', 'true', '2025-01-06 00:00:00', '2025-01-06 00:00:00');

-- 2025-02-06 21:03:29.8300
INSERT INTO "public"."ParamHeader" ("id", "description", "createdAt") VALUES ('GUIA', 'Ruta guía de usuario', '2024-09-08 15:52:05.115');
INSERT INTO "public"."ParamHeader" ("id", "description", "createdAt") VALUES ('INVEN', 'MOSTRAR INVENTARIO', '2024-09-08 15:52:05.115');
INSERT INTO "public"."ParamHeader" ("id", "description", "createdAt") VALUES ('LEGAL', 'Ruta legales', '2024-09-08 15:52:05.115');
INSERT INTO "public"."ParamHeader" ("id", "description", "createdAt") VALUES ('SCH_FIN', 'Hora final citas', '2024-09-08 15:52:05.115');
INSERT INTO "public"."ParamHeader" ("id", "description", "createdAt") VALUES ('SCH_INI', 'Hora inicial citas', '2024-09-08 15:52:05.115');
INSERT INTO "public"."ParamHeader" ("id", "description", "createdAt") VALUES ('SCH_INTERV', 'Intervalo de tiempo para citas', '2024-09-08 15:52:05.115');

-- 2025-02-06 21:03:45.0550
INSERT INTO "public"."Location" ("id", "name", "order") VALUES ('2cd1e428-eab1-4d31-9247-d32c6a36b79b', 'Costa Oeste', 3);
INSERT INTO "public"."Location" ("id", "name", "order") VALUES ('8592c79a-cba6-4bea-b33b-3a4fb0ddc1ee', 'CDMX', 1);
INSERT INTO "public"."Location" ("id", "name", "order") VALUES ('dadccb40-d7d6-4c04-ad85-832adec28a67', 'Costa Este', 2);

-- 2025-02-06 21:03:56.3860
INSERT INTO "public"."Group" ("id", "title") VALUES ('BACKOFFICE', 'Backoffice');
INSERT INTO "public"."Group" ("id", "title") VALUES ('DRIVER', 'Driver');
INSERT INTO "public"."Group" ("id", "title") VALUES ('MANAGER', 'Manager');

-- 2025-02-06 21:04:10.7180
INSERT INTO "public"."Checklist" ("id", "name", "order", "isDefault", "dismissible") VALUES ('KYC_DRIVER_INPUT', 'Aceptación de Contrato App UBER ', 0, 'false', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "isDefault", "dismissible") VALUES ('KYC_VERIFICATION', 'Verificación', 0, 'false', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "isDefault", "dismissible") VALUES ('ONBOARD', 'Preaprobación', 0, 'false', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "isDefault", "dismissible") VALUES ('VEHICLE_SETUP', 'Gestión del Vehículo / Preparación de Contrato', 0, 'false', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "isDefault", "dismissible") VALUES ('LEASING', 'Firma de Contrato y Entrega', 0, 'false', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('VEHICLE_TRACKER', 'Dispositivo de Trackeo', 32, 'VEHICLE_SETUP', 'false', 'true');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('VEHICLE_DOCUMENTATION', 'Documentación', 34, 'VEHICLE_SETUP', 'true', 'true');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('VEHICLE_STREET_TAG', 'TAG', 33, 'VEHICLE_SETUP', 'false', 'true');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('UBER_DRIVER', 'Aceptación de Contrato App UBER ', 35, 'VEHICLE_SETUP', 'true', 'true');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('VEHICLE_INVENTORY', 'Expediente de Vehículo', 31, 'VEHICLE_SETUP', 'false', 'true');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('UBER_VEHICLE', 'Vehículo', 36, 'VEHICLE_SETUP', 'true', 'true');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('PENDING_DOCUMENTS', 'Documentos de Vehículo', 1, 'VEHICLE_INVENTORY', 'false', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('ONBOARD_BACKOFFICE_APPROVAL', 'Aprobación de cliente', 1, 'ONBOARD', 'false', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('ONBOARD_MANAGER_APPROVAL', 'Aprobación del coordinador', 1, 'ONBOARD', 'false', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('VEHICLE_HANDOFF', 'Entrega del Vehículo', 40, 'LEASING', 'true', 'true');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('INACTIVITY_STATEMENT_VERIFICATION', 'Verificación de Comprobante de Inactividad', 26, 'KYC_VERIFICATION', 'false', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('INCOME_STATEMENT_VERIFICATION', 'Verificación de Otros ingresos', 27, 'KYC_VERIFICATION', 'false', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('DRIVERS_LICENSE_VERIFICATION', 'Verificación de Licencia de Conducir', 22, 'KYC_VERIFICATION', 'true', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('TAX_IDENTIFICATION_VERIFICATION', 'Verificación de Constancia de Situación Fiscal', 25, 'KYC_VERIFICATION', 'true', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('ADDRESS_VERIFICATION', 'Verificación de domicilio', 24, 'KYC_VERIFICATION', 'true', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('DELIVERY_DATE', 'Fecha de Entrega', 23, 'KYC_VERIFICATION', 'false', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('SELFIE_PICTURE_VERIFICATION', 'Verificación de Foto de Perfil', 23, 'KYC_VERIFICATION', 'true', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('KYC_GOOD_TO_GO', 'Confirmación de Arrendamiento', 31, 'KYC_VERIFICATION', 'true', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('KYC_MEET_LIVE', 'Durante la entrevista', 30, 'KYC_VERIFICATION', 'true', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('PAYMENT_VALIDATION', 'Pago Inicial Realizado', 29, 'KYC_VERIFICATION', 'false', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('IDENTIFICATION_CARD_VERIFICATION', 'Verificación de Identificación Oficial', 21, 'KYC_VERIFICATION', 'true', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('INACTIVITY_STATEMENT', 'Motivo de inactividad', 16, 'KYC_DRIVER_INPUT', 'false', 'true');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('KYC_MEET_SCHEDULE', 'Entrevista', 18, 'KYC_DRIVER_INPUT', 'true', 'false');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('SELFIE_PICTURE', 'Foto de Perfil', 11, 'KYC_DRIVER_INPUT', 'true', 'true');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('IDENTIFICATION_CARD', 'Identificación Oficial', 12, 'KYC_DRIVER_INPUT', 'true', 'true');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('ADDRESS', 'Domicilio', 17, 'KYC_DRIVER_INPUT', 'true', 'true');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('DRIVERS_LICENSE', 'Licencia de conducir', 13, 'KYC_DRIVER_INPUT', 'true', 'true');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('TAX_IDENTIFICATION', 'Constancia de Situación Fiscal', 15, 'KYC_DRIVER_INPUT', 'true', 'true');
INSERT INTO "public"."Checklist" ("id", "name", "order", "parentId", "isDefault", "dismissible") VALUES ('INCOME_STATEMENT', 'Otros ingresos (agregar yarea de monto)', 14, 'KYC_DRIVER_INPUT', 'false', 'true');

-- 2025-02-06 21:04:21.3560
INSERT INTO "public"."Campaign" ("id", "name", "isActive", "createdAt", "updatedAt") VALUES ('CMP1', 'Lanzamiento Autofin Rent', 'true', '2024-12-02 00:00:00', '2024-12-02 00:00:00');
INSERT INTO "public"."Campaign" ("id", "name", "isActive", "createdAt", "updatedAt") VALUES ('CMP2', 'Campaña concesionarios', 'true', '2024-12-02 00:00:00', '2024-12-02 00:00:00');

-- 2025-02-06 21:04:29.2740
INSERT INTO "public"."Branch" ("id", "name", "isPhysicalPlace") VALUES ('EDIF_INSURGENTES', 'Edificio Central Insurgentes', 'true');
INSERT INTO "public"."Branch" ("id", "name", "isPhysicalPlace") VALUES ('OFICINA_VIRTUAL', 'Oficina Virtual', 'true');
INSERT INTO "public"."Branch" ("id", "name", "isPhysicalPlace") VALUES ('SUCURSAL_1', 'Sucursal 1', 'true');
INSERT INTO "public"."Branch" ("id", "name", "isPhysicalPlace") VALUES ('SUCURSAL_2', 'Sucursal 2', 'true');

-- 2025-02-06 21:05:09.7610
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('07a6ece8-0286-41d3-ab82-b082cfe7c106', '8c20b789-0e81-44fa-95a3-861fcbbfa9d2', 'oauth', 'uber', 'partner.accounts.personal_info partner.accounts.personal_info.cpf partner.payments partner.trips vehicle_suppliers.partners.compliance vehicle_suppliers.partners.risk_profile.v3 offline_access partner.accounts', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAAF678np_TgYa4-zwlIxp7zNfAAAAKA8O8n32hBuwVhhGbNc6bajn5PHRI9_ejjDllstm1NwR9ieD4WKWDYMUFdcMDn9cQCRGzZynWRcDg5PXPiTeB0IJcHpCe7BnjmSAB0gHJzKGexms47mRSPYaPJLRTkwADAAAABj5DZgeW-Bz2hCunCQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2025-02-05 19:47:04.428', 1741376824, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdnqrjoL9-bTjy5TS7_9M_o67dNrxTYbIX-Phi3hCMXAzzugBT_Sr42L7BQcZPyQ8FmWvlGM8gAlZSoAYK2J0r4VQ==', 'MA.CAESEKG8PWU-MkJXtT44IKZuwgEiATEyATFCJDRmMjYwMmRmLWQzMmYtNGE3MS04OWQ2LWY3MjgxNzdlNmVlY0ogUXlyTllHN1IzaTctVWNaR3BaSkpjbFFsOWUzNWJVczhSJGMwMWQyNzk0LWQyYTktNGEzMS04ODVkLTEwNjBmMGQ3ZjNjZQ.Ba1IdmCrum-ryQ5w5HZ-B6R76uiagY6fx_wUYZpxhzQ.IpbP5kI0AaU-bPVHR1tN2GL9zW8W9nP2Fr6c_3UQY3Y', 'Bearer', '2025-02-05 19:47:04.428');
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('1bd1e90b-0616-4e3d-a1b2-4c671f308f8c', 'ede37a0d-4c40-4d19-b9c2-83c26db05484', 'oauth', 'uber', 'partner.accounts.personal_info.cpf partner.payments partner.trips vehicle_suppliers.partners.compliance vehicle_suppliers.partners.risk_profile.v3 offline_access partner.accounts partner.accounts.personal_info', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAACqRonRzF4m3qMFUrMOyN5dfAAAAu09XYVLM5CusYKq7vr3SxLr5RH3fjcz69HWC9fRcGymY1hrQm9vN6NqnuJyUZY3SkqYGyHfHeB58eY11cVHUI5Y0a7EyjdKA_WclDMCno-nK0n71rFZdJJ4FnBI0qccADAAAAHsUlQIhfVbSRUonuCQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2025-01-27 21:22:11.032', 1740604929, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdnbSANkTwQFlxvzs4AJkWqFJkEz2285Iyk7YQPT-KpqfS_Lu9LnMO4YsWHMBAj0isKd9pMnzPaTn8TmU5TolcyvA==', 'MA.CAESEN_whWAhSkO8i8bu30WcT5YiATEyATFCJGNjOGY5YWQ0LTUxNGYtNDJiYS1iYzgzLWIzNmE5ZjM1YjU5ZUogUXlyTllHN1IzaTctVWNaR3BaSkpjbFFsOWUzNWJVczhSJDU0MzU1OWYwLTMxMTYtNDlmZC1hYTk1LWJiZjJlMGEyNmRkMQ.6p3P8ZY39OZaCuzVVBDzXh0FwetZJ0cWvp8cN9p9GUc.Hp8tgGv-KVCfZ-AA80YDBNdMzKix811lrDylVQVlBvQ', 'Bearer', '2025-01-27 21:22:11.032');
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('2f610d89-31a2-40e7-94a0-6f21ce1e8507', 'e3c14ab2-7f57-4afc-8f59-2c0a98b6e15d', 'oauth', 'uber', 'partner.accounts partner.accounts.personal_info partner.accounts.personal_info.cpf partner.payments partner.trips vehicle_suppliers.partners.compliance vehicle_suppliers.partners.risk_profile.v3 offline_access', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAACx8P1EZG86uyvRYHwNOkZhfAAAA4Ex6oQwjsW8RSxxoamZclSud9Tloz67SkyBn82dbHAxrO4YJMx1Q_SylDqNS6Iy_TS1_m5SREFADrQxNjLZ7cLmINt-gwACG1UdO322VGfnn4y89wWSasnMOY_B597UADAAAACKdXBOf2_b0qG_YLSQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2024-09-21 18:54:46.903', 1729536885, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdnGLCgx-6C0h7M5uNwX-MBVdPeGtIuM451AjCAEODWwTKpCZhsCBqv37NFm_wItt2gwC9qS-seqZ7xyMhyJ8wjgw==', 'MA.CAESEL9xLifkdkwYmxSOx944naQiATEyATE.lTqkW7V4DLeYgJcU3pY1R3vcWJkhBYMXlsoZ-XTN6JI.vbw2aE8Vl7dgFQs1tBY2yx-KpH-o64vQ07TTaXg6fCY', 'Bearer', '2024-09-21 18:54:46.903');
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('30e3a8b7-aa6d-40b4-a045-48a479fa25ad', 'c00c185a-a4d9-4701-8dac-d3ceb54c02c3', 'oauth', 'uber', 'partner.accounts.personal_info partner.accounts.personal_info.cpf partner.payments partner.trips vehicle_suppliers.partners.compliance vehicle_suppliers.partners.risk_profile.v3 offline_access partner.accounts', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAALazSweBqNqbM6YTCLnaiX5fAAAA0_Mx7aNAUjtyaPnkQf00JoRcSgDThsfl6iiUuN082aLPbSvkoxR0S8BXGLYq-7K8l8_Ng6ZPCRYVUWRK-ifnQb8S6ds5jOnW7rm9UEFpWireFZZzJS6eBoEzKs4rmc0ADAAAANXSfvMQr7tmQ-VLfCQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2025-02-06 05:28:27.41', 1741411706, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdne8nKQtj7caTAfXZagCGiHj7Ug8Rx1McQbLYpr73zAwpxWTeaFUS6pLYAy1lSnyHDu7b5GVr_NjhJ_m3a1F7t1g==', 'MA.CAESELh_sxEQ00uTrdRusigWaW4iATEyATFCJDJhMWNlMGI0LWVkYTgtNGQxYS1iNzdmLTExNjQyZGMyMzg4ZkogUXlyTllHN1IzaTctVWNaR3BaSkpjbFFsOWUzNWJVczhSJGNjZDYxYzU5LTdlNDUtNGYzNC04ODcwLTI5MDM3NGNlZGQ0Nw.EONwrD5cdMbGMts6mzcOcD67OkOCbBW2aNTDytKNxAQ.Ho08ZJhmisN97gYiDwYLhsPRCnPKp1_I9ZdpOST-O28', 'Bearer', '2025-02-06 05:28:27.41');
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('3c589bbe-dde7-4cd8-bf98-26693e33c267', 'dd8b5b17-a4df-41a5-94e5-36460eb65f71', 'oauth', 'uber', 'offline_access partner.accounts partner.accounts.personal_info partner.accounts.personal_info.cpf partner.payments partner.trips vehicle_suppliers.partners.compliance vehicle_suppliers.partners.risk_profile.v3', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAAD51RcLcVpw7Y8sXwGAn5SlfAAAAiuwR98rftnhPNp74kgLA3LZfZwqfcAKCMqABou7C351tui79OzcmF3b-hGOygW3NvW6dT-xYr41iDiWyHM0Gwxj2efj6dlpWitoNk_N6qWxJPZ2vIkJyC-27j-CNK_wADAAAAK88mqYkHJz8A78nWCQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2024-05-19 21:56:43.625', 1718747802, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdnLoixUdTgJx7zd-aXAd9Gml_xrsbgM59ua9gibVE_mty6o2yhqVkZk6s1crxRJ0K5jw9KxqTSoEwX8m0u9alocw==', 'MA.CAESEEjGbDilhkMUoVnwcSj8GLEiATEyATE.f1RbvGtV338xmi6cYjQDvihzXnhNtsVLyZHgUd7Eij0.2lQRgB_ikxYMol1EU-C7nGmK924QdW2bXhvJUV0ZGFc', 'Bearer', '2024-05-19 21:56:43.625');
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('3f7518c6-a86e-476e-b2c7-5bc86aef7483', 'c7f6f4f0-c9b9-4090-b74a-1d88253c1d61', 'oauth', 'uber', 'partner.payments partner.trips vehicle_suppliers.partners.compliance vehicle_suppliers.partners.risk_profile.v3 offline_access partner.accounts partner.accounts.personal_info partner.accounts.personal_info.cpf', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAAHZhrzTwss1M2zLi3tCqDm1fAAAAR0NzUAIcBaNW6ISCKVv0PAAzOoh1ZaggiiEULMmIe2kh61fGg5o3RNP02wZtqIk-bS-FExais39f1pbNYUsznGTPBgAcsTP9eXj05VMsdbeeufCFyM16tOsurxGvRQQADAAAAFlxDpyeLwdvy8MG0SQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2024-11-29 20:00:14.843', 1735502413, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdn-0D3xAFINkonrG89cQY5WgfcTBPEfwyuyp4gTeE6L_PK4p_N3ruid8YkSTNLlyzvn01msBTEfax2p7S-aFDKGg==', 'MA.CAESECOiuGmIQ0KLrBU6vb_qA3EiATEyATFCJGIxMTZlMGVlLTQyMzItNDNhYy1iNDQ4LTg2NzFhOWVhNzc5NUogUXlyTllHN1IzaTctVWNaR3BaSkpjbFFsOWUzNWJVczhSJDQ1ZWZkNjg0LTYxN2YtNDBiNS1iZWVhLTkyOTQ1M2ZhZmIxZg.ySj78wmSzHAFuP2SEj1y5uVR9FOvKd_SBTB-tdHeD1I.yuytpHmqinl4NOAt0UNrARrTAFMY0k52klUJW7bFeLQ', 'Bearer', '2024-11-29 20:00:14.843');
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('5ca87b00-41af-4714-b326-6973cc1946a8', 'd0933019-cca3-4b6b-bcd2-e033637c5b2b', 'oauth', 'uber', 'offline_access partner.accounts partner.accounts.personal_info partner.accounts.personal_info.cpf partner.payments partner.trips vehicle_suppliers.partners.compliance vehicle_suppliers.partners.risk_profile.v3', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAACzK2uQ9xoAS6LYbyT8HRZZfAAAAaP6n2_iJ_7CsMzYDFW5bKnsdeQyQ4BsgNsu7x3zgjSzEL9saTlf1swF8qjZzOm6W_elpX2GVL9DRq1r614IXS0bbwy4Elm00GAMKiJSZQWFxIJ4W1iGSarnmXOAL62wADAAAAI04LKPq184SDJ5KaiQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2024-10-09 13:57:22.19', 1731074241, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdn9wCSNwUIjU-fl-kbM7inIyo7MRTasvGfFoUM7ul-R0y2HpkB6uzlBAsvy8qaxUjUqMkhU_chnL2JoGjXrZB-RQ==', 'MA.CAESEJJMcVAfC0V4j7R7bENox8siATEyATFCJDFkMzNmZWMzLWYxYTktNGVhYi1iOTJlLTcyZGQ1ODliN2RlOUogUXlyTllHN1IzaTctVWNaR3BaSkpjbFFsOWUzNWJVczhSJDI1OGQxMTg0LThiY2QtNDNlNi1iZmNjLWNkMGFmMDNkNWUyNQ.3yhOq8fbsFnhXdQArIZqvNP6iimAqo0nIOtoyUHQLBE.04MxLVE1rRMOoVlFSQ_XY4WocNp3cOGqNdX4VIaukg0', 'Bearer', '2024-10-09 13:57:22.19');
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('6c5bb112-c8d0-40d0-8bd9-ff321cd81af9', '7ff4c8e8-81c3-4d80-b984-715db25d3d94', 'oauth', 'uber', 'vehicle_suppliers.partners.compliance vehicle_suppliers.partners.risk_profile.v3 offline_access partner.accounts partner.accounts.personal_info partner.accounts.personal_info.cpf partner.payments partner.trips', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAAFFfEMh2oaAIIsSQgmz8tSdfAAAA9kba_i4XbrTn1DYr4acr11o9NrdCHnHpBtX5-VGCymsAuvMWpP7-ym6jq-xgNSTzknpCoUtAw8XnEIpR6ZG6y4fOSZpU44gkNHhS84RWBEW6HtCKBVB4JbYINYkyoZIADAAAAGLVrhPEkMF7mv7ULSQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2024-09-02 19:31:28.145', 1727897487, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdnW48erJQwC74SXKk_fBGalWfMGyAQhgSANleTInizyCDnYm_iYI3qnj4GBsy99CgTVzGUs-Kptp_h21FHDlQvXA==', 'MA.CAESEC3SbsmCo0AQl7awjc9y2_UiATEyATE.MFN-GccbGN9F5MiMO7A1sehELkoYD1g9BdiDTeTI2LM.hqJOzk4DPkeWuO7reThvM4obGcgvUb74sbRs_8LcKR8', 'Bearer', '2024-09-02 19:31:28.145');
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('6d022f7f-680b-4351-bbff-675c2d82213b', '31c36cfa-7800-473d-875a-92cf067d20cf', 'oauth', 'uber', 'partner.trips vehicle_suppliers.partners.compliance vehicle_suppliers.partners.risk_profile.v3 offline_access partner.accounts partner.accounts.personal_info partner.accounts.personal_info.cpf partner.payments', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAAOTAu6vnshR3hElbj4gq92FfAAAAEBxaXef5MvP89KemcdjoEC6jToV7LvdruxEUgjDbF1c4hMmw7UzOQnc9UVqSfkRkcYx7EnwpifFSZIzNt-ERZ_SUPfY7gVr4m24x7uBRScZ7_demeqz9dxQ9M5yftewADAAAAMDQ0QRFqtgmAf9VsSQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2024-07-17 20:46:53.175', 1723841212, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdnTM3Zjv3ho_Y3At18kEg6bXsK50_5N-qt41QqH-vB9cUZE69YvtkdsOA7sQW2_r3tNTE1hEemIL8yEsH0cqaBgQ==', 'MA.CAESEE_q-mtsIUeJmZSphc548UciATEyATE.WJ2suIouBlHZDX3bOvcAFjkvEnr9RbvZ0TijnCbvOuM.Rzi8r-hQdp6uFcU7XWxI9ls7KHlJ7Lvn52B7gSEmucQ', 'Bearer', '2024-07-17 20:46:53.175');
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('a29cd6f6-6f73-43eb-bac1-0a20dfb15d49', 'e22ed751-fbcf-4c4e-be58-740981d1ff87', 'oauth', 'uber', 'partner.accounts.personal_info.cpf partner.payments partner.trips vehicle_suppliers.partners.compliance vehicle_suppliers.partners.risk_profile.v3 offline_access partner.accounts partner.accounts.personal_info', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAAIKaZ491JcgO2rykgk7ifftfAAAAG7LRC1FLqU7yXxVpaJheEi083_HyNUka8W2tt4wZm0dV0415737KQ2mXtilJDI4wXjGfaFufLRTDsHOz5YVlnbvkeorAL5R4PGoiWnFB3b6v8fJnt6EhdrzObp3LH2AADAAAAEF5F4SaOLvNYYFcPCQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2025-02-05 13:39:38.516', 1741354778, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdnQOVi6sV0BTNCpNBDKDhrojZBIgZe4HvWOB1M99bsHOnFuJxdulGZS3RGlfQjjTfR3cCaV04A-ysGTjikBNrIbQ==', 'MA.CAESENZdW6DAuU7tu2CXAmXJkP8iATEyATFCJDQxZmEzOGFiLWRmOGQtNDgxZi04MDQ0LTJkYWJlZmFhMGJkMkogUXlyTllHN1IzaTctVWNaR3BaSkpjbFFsOWUzNWJVczhSJDQzODEwYjQxLTc1MDQtNGI5NS1iMWZlLTI0ZGI0MDdhNmIyNw.L9idE6lP07FdJPr9qCAguO6vk25lNUAEn7l3QEJvCCk.R80N8A-4dCdmAt1RdnV8VF5UP8GRftjrSbolM9pL1dM', 'Bearer', '2025-02-05 13:39:38.516');
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('a923dbb3-684e-4c45-93d7-7a1b1eda342a', '5dff2b92-0b41-4fb7-886f-d495c13ee6c9', 'oauth', 'uber', 'partner.accounts.personal_info partner.accounts.personal_info.cpf partner.payments partner.trips vehicle_suppliers.partners.compliance vehicle_suppliers.partners.risk_profile.v3 offline_access partner.accounts', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAAJYj2eKxseH_t7QmeyDofwlfAAAAddvVhkARodNqP0ArVj4QHLmc9a7SRtUBabQmUGJ46NkJSH3j26nxe8p7GzidVSjz3s0Cdbcqx-PF5LnQHErd5NsBoWDREuzCCqQ3RBUuWPZc6M8eqAqaUYC6K0GHYbsADAAAAG1LVVdw4Gh7UAKkACQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2024-09-02 16:30:46.667', 1727886645, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdnPjvjuXniYvI5egwDAANrMt-ljy-1_pgQQ7N3SN9FjpWYeRukVNt6fZBuoFTfGNUZUpk_JClq8uuY6jUj_ZP5uw==', 'MA.CAESENQr8s8rTUQHs5CJabG5NF8iATEyATE.eKdZA7btk9NvqoPxLms8FsDZZo5zjOKqf4V-KzYcURw.BAwp9Ut8ZMeJceCyN_YHzF7jIsxmbqzYY02DbyvafpM', 'Bearer', '2024-09-02 16:30:46.667');
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('aa6761a1-cad8-42a0-8904-cb91ff7b3e55', 'e4c1412c-ecfc-4a78-a84a-d5e9aad610e5', 'oauth', 'uber', 'partner.accounts partner.accounts.personal_info partner.accounts.personal_info.cpf partner.payments partner.trips vehicle_suppliers.partners.compliance vehicle_suppliers.partners.risk_profile.v3 offline_access', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAANlyGdm47-6dxn4imj44N5lfAAAAWGDKEJlDB3VciUFecBkaAIMWz3DqKaUK8HZVqcCZnN5suKybvG4KpL6d1WTEVTM5KAJfZEz2qZi4_RjKqVYWJRHIiHXYS8MhInQJcVL1UE4NiCezCwn8ueHstzAp_4IADAAAAPyOfzm59Z5tsHS55iQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2024-08-29 16:27:04.757', 1727540823, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdnh98QrC3MH646gtVv4sYFemaAvPwwvlDI-3eyGnLNc7vlFS8B_h3H7Lo0qwt4pQvnoP5x5cHOlvbxDKk5gAWahQ==', 'MA.CAESEAqrOm5HLkb5ngmTGF0HVpEiATEyATE.FzIuJcH6FrkjbQUWL3bRW9t1cBZHwVdvObkp8VOeqks.SWDnJOxyAJCoCrTyVVwzExlDCaqYPrTHd2HoJ2fC3RQ', 'Bearer', '2024-08-29 16:27:04.757');
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('ad67d20a-aefb-4093-b564-b338cf310fe6', 'a2b2a150-cf44-499b-8d8a-565f938abdf2', 'oauth', 'uber', 'partner.accounts.personal_info partner.accounts.personal_info.cpf partner.payments partner.trips vehicle_suppliers.partners.compliance vehicle_suppliers.partners.risk_profile.v3 offline_access partner.accounts', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAAMhYG_dJttIlcBE-B4rQjOZfAAAAWsPSIWvTdBSH1YlEVrFt3hKa9_NRP2DVlZ06O1KimhcpswVKnLvLnNT3S83Y56m_4yyf7StWd1UTyzxfoD148adFLa0D0dvGK7DslmU-OXZH8Mbmzc29p9yFB6knn1wADAAAAN6jsvl6SuTYJyJJXSQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2024-09-19 23:02:29.299', 1729378948, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdn6AGIQhxFMqZ8BjpUtdrqBjYAr-hlmotBg5-I2gbvVQYcnMmOeuTWFcoWoOzy5qC-BcWjrnxYMj6zFGQmDlaE9A==', 'MA.CAESEOjf87MlsUENgYvUx2nFEnQiATEyATE.TCsSaPkAWczfsn-SgwY0Lf7_a2BKnK6u5DXqnC6COaY.8hOiWz5u5AzHMxnNci71l6f7iJ-cVUbsqOMv5Xqgi0A', 'Bearer', '2024-09-19 23:02:29.299');
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('ae27b5b0-138e-4cb8-a4b4-9e88960b55f3', '2c26471b-cb6c-4d0b-a082-74204400be8f', 'oauth', 'uber', 'partner.payments partner.trips vehicle_suppliers.partners.compliance vehicle_suppliers.partners.risk_profile.v3 offline_access partner.accounts partner.accounts.personal_info partner.accounts.personal_info.cpf', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAAMaCCtv1oMxr71QwHunO4VFfAAAAWPd2VS6aenK_lWBw3WGFmUHZvpqx77UxoAThQbQ2XqytjCtmoNkv1OaUedcYDAAR3U0gbwd8zacH5W-khgOad3ddXbUztV2JwpaI0mETBag3BgxRzhHaQXDRv2Ji7_sADAAAAM_XlpFbuR08W0bQAyQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2025-01-29 12:18:18.741', 1740745095, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdnI-m3_BMrRUBunmOiYI59Jyw2v6uKbQxhbPZHGmgkuP2GokjfI-ql0rf8tRAIo6HRauwQA7Xfxn9jQ-3vmxW85Q==', 'MA.CAESEL-N0PYaRkEWk5AEzc4wP_AiATEyATFCJDhiN2Q4OTFkLTNlZmQtNDNlYS04MTZjLWIxOGUzMjUwMjI2ZEogUXlyTllHN1IzaTctVWNaR3BaSkpjbFFsOWUzNWJVczhSJDA1OGU5MTM3LWFkZDUtNDBlOC04ZDc1LTc0OTA0ZTYyMjkyYw.gEN-mFQwgh5h9xPC0FPhM9U4U0vm-ad_CR7g1Oj_CxM.2Kqk6neujsWoAtrv0zm1h-gTd8tht-yZqvkxtNLunB8', 'Bearer', '2025-01-29 12:18:18.741');
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('bdbc171b-ca88-4dcc-b0e6-81b6086422e2', '18345dba-5db3-4f06-85a6-6cce0c724411', 'oauth', 'uber', 'partner.accounts partner.accounts.personal_info partner.accounts.personal_info.cpf partner.payments partner.trips vehicle_suppliers.partners.compliance vehicle_suppliers.partners.risk_profile.v3 offline_access', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAALA0BklY4GRuBFEOHpPPyEtfAAAArUZvKJMAzm9FdA94g5ssXbxSNE66Ff58NimoePRCDlo6u055-vgCH_BgTI1CCMZrsQFYCubs2Uny8mQXcXe3RGh0j4eBsyJM_QOAH2AV-JUAgYNmPmcFnMnAdGmyNXwADAAAAE5QAQcPEioyDCncsCQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2025-02-05 23:13:19.79', 1741389198, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdnhsmWQ3JIjz55xAsAql5mJrvnYvIcvSPiGzPiORn77gwAYtuMaS3zLPk_xG9AwV34v977Z9j5ky3V71yTYngW1A==', 'MA.CAESENbjqtfuEUvWgw8kCwfNK-MiATEyATFCJGY3YzVkMmZiLTcyNmItNDE1MS04YzIzLWMxOGZkNTJjMWIzNUogUXlyTllHN1IzaTctVWNaR3BaSkpjbFFsOWUzNWJVczhSJDQzZTdjMjUwLTMwNTYtNGFlMi1iZWY5LTc1OGVlYmIyOTI0OA.-YHduwJdVsgY7kbU8Vve7PlTYbtJpAp9YdYji-uOJ0w.YhfOnyzwpmTCLV3BYD3U4EET_rwW08QWE1H9N3W2DSQ', 'Bearer', '2025-02-05 23:13:19.79');
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('c55695f8-5ad9-46e3-8c08-34e24303bace', 'fdee63ee-aaba-4793-90c9-93ff878caf9e', 'oauth', 'uber', 'vehicle_suppliers.partners.risk_profile.v3 offline_access partner.accounts partner.accounts.personal_info partner.accounts.personal_info.cpf partner.payments partner.trips vehicle_suppliers.partners.compliance', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAAHnR7iiiiR1cnzhk48h93ixfAAAAjCTtl5b1hkcnz56FlzhMeRJYKt7FXigQ0R7JHCWyFXG8UDccyz6n6hcLyY7aa135oavFI63qOy2GLQ-ksiawK-3xBy9F7J0U2zQILNu3mKDLIDbSG7dSN7jEl_GzKHwADAAAABmXmh-g5rGiSEX9IiQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2024-09-18 17:00:39.961', 1729270839, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdnGSdBBzG7GRuXif5Pf-itezyvOjV374jhDX13PXCMVrNCwr_rs9eR9jgU9k0eRvq-LcCHxTlYT7joAvRAzEnF-g==', 'MA.CAESEAFuPlkifETdr9WtNJJexjwiATEyATE.aoi1gdD3pSfCVZckg-KvYTxuwXCMDx0kKF7MnH9UORk.OBguoiJGCXInEERpNvJUXS11IujsLvyKZNor2BuakNA', 'Bearer', '2024-09-18 17:00:39.961');
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('dcdef04b-d452-4ee8-8de7-b76019e14f6c', '3e6a6897-2a85-4051-a263-d63a74a6f3c3', 'oauth', 'uber', 'vehicle_suppliers.partners.risk_profile.v3 offline_access partner.accounts partner.accounts.personal_info partner.accounts.personal_info.cpf partner.payments partner.trips vehicle_suppliers.partners.compliance', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAAB9Se4B7MGWUaMtVjaCxrf5fAAAAXApQbmZJ38dlf0AE4SW9u73nuo5ybq4dvBrR-6UErOYw1wg4yzugGaf3URgTfAEpeq57hw8TvYkso6BrM22w1n3UyOadepPbtl_XlToFNSxzqqqFisfap533bZ-xsn0ADAAAAEcwP6Ahex0JYrzODCQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2024-07-19 16:35:24.072', 1723998923, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdnpukcyEKh2DaAJ8mtsLwwOa50ZumzCrQCvXQAc96BAkDZ3xiOPJLpwktV_SlUCUlbAlr9-Y3fhK-QSBgBeOX5pA==', 'MA.CAESENjpfXSEx0gzuFbbd_S3pcciATEyATE.Z8vbVTnN0FNf33sBxsvyeUJKxi7IEx_xTohtiPmN8Nk.JfdKBl6mlLZGbVZSwEnUB1WedHrBdDx7yeCXXHzl22M', 'Bearer', '2024-07-19 16:35:24.072');
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('edaf2e1b-61f9-4b90-a5ec-3433b9c88809', 'd2766526-2d20-4168-a401-878358a51604', 'oauth', 'uber', 'partner.trips vehicle_suppliers.partners.compliance vehicle_suppliers.partners.risk_profile.v3 offline_access partner.accounts partner.accounts.personal_info partner.accounts.personal_info.cpf partner.payments', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAANQntBGYu31yzfNnSoAhpbdfAAAAlqEo55jHMjkoN__iu5ZxGwp_4uxGl2ZupdiYGebApFQ9_LD29S9aPvw-wJfNUVxWXyw7eY86c-DrpDcd7Q9w2XhUPONedfZilYkMkrNAEIy4Yu6j4KhfCX3Syf58qA8ADAAAAGhMyjptDnK4GOd8FCQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2024-10-04 22:07:00.228', 1730671619, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdnC_RADoVIhJeEOvlUXpHnOMI9WFhdhuW2twjk_PAaBj56UDhmZCWmn9AX_xT77pqUmPN0z51lHhJ025yaGkpFpg==', 'MA.CAESEPvWRFX_m0K_m3bj45IamUAiATEyATFCJDZhYzcxYTZkLWUyNGUtNDk4OC05YzJmLWZkMTFiMjE0ZmZjMkogUXlyTllHN1IzaTctVWNaR3BaSkpjbFFsOWUzNWJVczhSJDMxZDk4M2Q0LTc4ZTMtNDFjZS04Y2YwLWYxNjliZDg0YWE2NA.WC8W5WQeY_-fWmQz7J4NpNtd2XsqrTjIcaz_jqF_6UY.Jsbei__qTwae9RZu0agAgoL43_uGg-8a69pM0h-fUgs', 'Bearer', '2024-10-04 22:07:00.228');
-- INSERT INTO "public"."Account" ("id", "userId", "type", "provider", "scope", "access_token", "created_at", "expires_at", "provider_account_id", "refresh_token", "token_type", "updated_at") VALUES ('f03b266c-f9f1-4cd0-b8a6-885131ae3177', '5e00345e-fa20-4136-a8f0-f3b7fbfc02ab', 'oauth', 'uber', 'partner.accounts partner.accounts.personal_info partner.accounts.personal_info.cpf partner.payments partner.trips vehicle_suppliers.partners.compliance vehicle_suppliers.partners.risk_profile.v3 offline_access', 'IA.VUNmGAAAAAAAEgASAAAABwAIAAwAAAAAAAAAEgAAAAAAAAGwAAAAFAAAAAAADgAQAAQAAAAIAAwAAAAOAAAAhAAAABwAAAAEAAAAEAAAAGnLmdDCCyh6jVbAal2Oq5RfAAAAf7jtigETParPXb7HGZy017nyN5DYEvVhRir8KyswZZ5lpPdF2lpZYlGriP5MKPwkupQC5B7DVfsrpb25N_B1c5geGKCg5IhLhOXnRCQvqn8xO14Kgdmz0wrSMUaFHHgADAAAAOI4LGS_hYMKbCMo2SQAAABiMGQ4NTgwMy0zOGEwLTQyYjMtODA2ZS03YTRjZjhlMTk2ZWU', '2024-07-15 16:04:08.457', 1723651447, '8Ol_cGFRWxNl4edmLn9luXAPzzPm31B638yrCxqzWcdnRsc3sOr_uuUbfE8evnrLG78luxt_jFIu1mdlc3ir9Ms4FIs52wLiQLiADJkyPSEp7LlQbngYvDH7-Yw1fV6cLw==', 'MA.CAESEEBUepyx7kZBqPVxQmQesoUiATEyATE.m_upRuliNUiJvaqMNBKBiCPShBSYFrFzFT1oHfrb1CM.abOgySIAMbTH1LIqi55t9ftn7VcjS7131_lhF5YCSk8', 'Bearer', '2024-07-15 16:04:08.457');

-- -- 2025-02-06 21:05:17.7760
-- INSERT INTO "public"."UserGroup" ("userId", "groupId", "assignedAt") VALUES ('1f4b9a5a-9759-4052-84f6-97373d98964f', 'BACKOFFICE', '2024-08-28 22:16:11.217');
-- INSERT INTO "public"."UserGroup" ("userId", "groupId", "assignedAt") VALUES ('2c30073e-e3a8-4be5-9269-04479c74e468', 'BACKOFFICE', '2024-10-09 15:53:42.96');
-- INSERT INTO "public"."UserGroup" ("userId", "groupId", "assignedAt") VALUES ('40304bc2-9e78-43f0-b4a7-d5a460a22c7e', 'BACKOFFICE', '2025-01-20 21:38:16.52');
-- INSERT INTO "public"."UserGroup" ("userId", "groupId", "assignedAt") VALUES ('5faaa08f-d393-4c7f-9735-723cb42bc199', 'BACKOFFICE', '2024-06-17 13:43:35.7');
-- INSERT INTO "public"."UserGroup" ("userId", "groupId", "assignedAt") VALUES ('76e46768-c65e-4aab-9e16-11cae6c40bd5', 'BACKOFFICE', '2024-06-17 13:43:35.693');
-- INSERT INTO "public"."UserGroup" ("userId", "groupId", "assignedAt") VALUES ('c387646e-4ff6-4267-b7c2-8e1283040240', 'BACKOFFICE', '2024-06-17 13:43:35.693');
-- INSERT INTO "public"."UserGroup" ("userId", "groupId", "assignedAt") VALUES ('c75f2a56-921a-4a34-8cfb-7be4336474a4', 'BACKOFFICE', '2024-09-25 16:25:38.322');
