apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{APP_NAME}}-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app: test-{{APP_NAME}}

spec:
  tls:
    - hosts:
        - {{APP_NAME}}.test.afprojects.net
      secretName: test-{{APP_NAME}}-letsencrypt-traefik
  rules:
    - host: {{APP_NAME}}.test.afprojects.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-{{APP_NAME}}-svc
                port:
                  number: 3000
  