apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: test-
configMapGenerator:
- behavior: merge
  envs:
  - config.properties
  name: uber-config
transformers:
- |-
  apiVersion: builtin
  kind: NamespaceTransformer
  metadata:
    name: notImportantHere
    namespace: uber
    unsetOnly: true
resources:
- ../base/
patches:
- path: ingress.test.yaml
- patch: |-
    - op: replace
      path: /metadata/labels/app
      value: test-uber-api
    - op: replace
      path: /spec/selector/matchLabels/app
      value: test-uber-api
    - op: replace
      path: /spec/template/metadata/labels/app
      value: test-uber-api
  target:
    kind: Deployment
- patch: |-
    - op: replace
      path: /spec/selector/app
      value: test-uber-api
    - op: replace
      path: /metadata/labels/app
      value: test-uber-api
  target:
    kind: Service
- patch: |-
    - op: replace
      path: /metadata/labels/app
      value: test-uber-api
  target:
    kind: ConfigMap