apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{APP_NAME}}-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app: {{APP_NAME}}

spec:
  tls:
    - hosts:
        - {{hostname}}
      secretName: {{APP_NAME}}-letsencrypt-traefik
    - hosts:
        - www.{{hostname}}
      secretName: {{APP_NAME}}-letsencrypt-traefik
  rules:
    - host: www.{{hostname}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{APP_NAME}}-svc
                port:
                  number: 3000
    - host: {{hostname}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{APP_NAME}}-svc
                port:
                  number: 3000
