apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
configMapGenerator:
- behavior: merge
  envs:
  - config.properties
  name: web-autofinrent-config
transformers:
- |-
  apiVersion: builtin
  kind: NamespaceTransformer
  metadata:
    name: notImportantHere
    namespace: autofinrent
    unsetOnly: true
resources:
- ../base_prod/
patches:
- path: ingress.web-autofinrent.yaml
- patch: |-
    - op: replace
      path: /metadata/labels/app
      value: web-autofinrent
    - op: replace
      path: /spec/selector/matchLabels/app
      value: web-autofinrent
    - op: replace
      path: /spec/template/metadata/labels/app
      value: web-autofinrent
  target:
    kind: Deployment
- patch: |-
    - op: replace
      path: /spec/selector/app
      value: web-autofinrent
    - op: replace
      path: /metadata/labels/app
      value: web-autofinrent
  target:
    kind: Service
- patch: |-
    - op: replace
      path: /metadata/labels/app
      value: web-autofinrent
  target:
    kind: ConfigMap