import { Collection } from '@domain/kernel/Collection'
import { TaskType } from './models/TaskType'
import { TaskTypeConfig } from './TaskManager'
import { APPLICATION_BACKOFFICE_APPROVAL } from './implementations/APPLICATION_BACKOFFICE_APPROVAL'
import { APPLICATION_MANAGER_APPROVAL } from './implementations/APPLICATION_MANAGER_APPROVAL'
import { KYC_SELFIE_PICTURE_UPLOAD } from './implementations/KYC_SELFIE_PICTURE_UPLOAD'
import { KYC_ADDRESS_INPUT } from './implementations/KYC_ADDRESS_INPUT'
import { KYC_ADDRESS_PROOF_UPLOAD } from './implementations/KYC_ADDRESS_PROOF_UPLOAD'
import { KYC_ADDRESS_PROOF_JOB } from './implementations/KYC_ADDRESS_PROOF_JOB'
import { KYC_ADDRESS_VERIFICATION } from './implementations/KYC_ADDRESS_VERIFICATION'
import { KYC_DRIVERS_LICENSE_JOB } from './implementations/KYC_DRIVERS_LICENSE_JOB'
import { KYC_DRIVERS_LICENSE_UPLOAD } from './implementations/KYC_DRIVERS_LICENSE_UPLOAD'
import { KYC_DRIVERS_LICENSE_REVERSE_JOB } from './implementations/KYC_DRIVERS_LICENSE_REVERSE_JOB'
import { KYC_DRIVERS_LICENSE_REVERSE_UPLOAD } from './implementations/KYC_DRIVERS_LICENSE_REVERSE_UPLOAD'
import { KYC_DRIVERS_LICENSE_VERIFICATION } from './implementations/KYC_DRIVERS_LICENSE_VERIFICATION'
import { KYC_IDENTIFICATION_CARD_JOB } from './implementations/KYC_IDENTIFICATION_CARD_JOB'
import { KYC_IDENTIFICATION_CARD_UPLOAD } from './implementations/KYC_IDENTIFICATION_CARD_UPLOAD'
import { KYC_IDENTIFICATION_CARD_REVERSE_JOB } from './implementations/KYC_IDENTIFICATION_CARD_REVERSE_JOB'
import { KYC_IDENTIFICATION_CARD_REVERSE_UPLOAD } from './implementations/KYC_IDENTIFICATION_CARD_REVERSE_UPLOAD'
import { KYC_IDENTIFICATION_CARD_VERIFICATION } from './implementations/KYC_IDENTIFICATION_CARD_VERIFICATION'
import { KYC_INACTIVITY_STATEMENT_JOB } from './implementations/KYC_INACTIVITY_STATEMENT_JOB'
import { KYC_INCOME_STATEMENT_JOB } from './implementations/KYC_INCOME_STATEMENT_JOB'
import { KYC_SELFIE_PICTURE_VERIFICATION } from './implementations/KYC_SELFIE_PICTURE_VERIFICATION'
import { KYC_TAX_IDENTIFICATION_JOB } from './implementations/KYC_TAX_IDENTIFICATION_JOB'
import { KYC_TAX_IDENTIFICATION_UPLOAD } from './implementations/KYC_TAX_IDENTIFICATION_UPLOAD'
import { KYC_TAX_IDENTIFICATION_VERIFICATION } from './implementations/KYC_TAX_IDENTIFICATION_VERIFICATION'
import { KYC_SELFIE_PICTURE_JOB } from './implementations/KYC_SELFIE_PICTURE_JOB'
import { KYC_INCOME_STATEMENT_VERIFICATION } from './implementations/KYC_INCOME_STATEMENT_VERIFICATION'
import { KYC_INCOME_STATEMENT_UPLOAD } from './implementations/KYC_INCOME_STATEMENT_UPLOAD'
import { KYC_INACTIVITY_STATEMENT_VERIFICATION } from './implementations/KYC_INACTIVITY_STATEMENT_VERIFICATION'
import { KYC_INACTIVITY_STATEMENT_UPLOAD } from './implementations/KYC_INACTIVITY_STATEMENT_UPLOAD'
import { KYC_MEET_ADDRESS_MATCH } from './implementations/KYC_MEET_ADDRESS_MATCH'
import { KYC_MEET_CONFIRM_DATE } from './implementations/KYC_MEET_CONFIRM_DATE'
import { KYC_MEET_PICK_DATE } from './implementations/KYC_MEET_PICK_DATE'
import { KYC_MEET_CANCEL_DATE } from './implementations/KYC_MEET_CANCEL_DATE'
import { KYC_MEET_HOST_INVITATION } from './implementations/KYC_MEET_HOST_INVITATION'
import { KYC_MEET_GUEST_INVITATION } from './implementations/KYC_MEET_GUEST_INVITATION'
import { LEASING_CONTRACT_SIGNATURE } from './implementations/LEASING_CONTRACT_SIGNATURE'
import { UBER_DRIVER_CONTRACT } from './implementations/UBER_DRIVER_CONTRACT'
import { UBER_VEHICLE_REGISTRATION } from './implementations/UBER_VEHICLE_REGISTRATION'
import { VEHICLE_ASSURANCE } from './implementations/VEHICLE_ASSURANCE'
import { VEHICLE_AUTHORIZATION } from './implementations/VEHICLE_AUTHORIZATION'
import { VEHICLE_HANDOFF_CANCEL_DATE } from './implementations/VEHICLE_HANDOFF_CANCEL_DATE'
import { VEHICLE_HANDOFF_CHECKIN } from './implementations/VEHICLE_HANDOFF_CHECKIN'
import { VEHICLE_HANDOFF_CONFIRM_DATE } from './implementations/VEHICLE_HANDOFF_CONFIRM_DATE'
import { VEHICLE_HANDOFF_PICK_DATE } from './implementations/VEHICLE_HANDOFF_PICK_DATE'
import { VEHICLE_INVENTORY_RELEASE } from './implementations/VEHICLE_INVENTORY_RELEASE'
import { VEHICLE_INVENTORY_RESERVE } from './implementations/VEHICLE_INVENTORY_RESERVE'
import { PENDING_DOCUMENTS } from './implementations/PENDING_DOCUMENTS'
import { VEHICLE_STREET_TAG_INSTALLATION } from './implementations/VEHICLE_STREET_TAG_INSTALLATION'
import { VEHICLE_TITLE } from './implementations/VEHICLE_TITLE'
import { VEHICLE_TRACKER_INSTALLATION } from './implementations/VEHICLE_TRACKER_INSTALLATION'
import { VEHICLE_TRACKER_SIM } from './implementations/VEHICLE_TRACKER_SIM'
import { KYC_INACTIVITY_STATEMENT_INPUT } from './implementations/KYC_INACTIVITY_STATEMENT_INPUT'
import { KYC_FINAL_APPROVAL } from './implementations/KYC_FINAL_APPROVAL'
import { PAYMENT_CHECKOUT } from './implementations/PAYMENT_CHECKOUT'
import { PAYMENT_RECONCILIATION } from './implementations/PAYMENT_RECONCILIATION'
import { PAYMENT_VALIDATION } from './implementations/PAYMENT_VALIDATION'
import { DELIVERY_DATE } from './implementations/DELIVERY_DATE'

export const taskTypeCollection = new Collection<TaskTypeConfig>()
  .set(TaskType.APPLICATION_BACKOFFICE_APPROVAL, APPLICATION_BACKOFFICE_APPROVAL)
  .set(TaskType.APPLICATION_MANAGER_APPROVAL, APPLICATION_MANAGER_APPROVAL)
  .set(TaskType.KYC_SELFIE_PICTURE_UPLOAD, KYC_SELFIE_PICTURE_UPLOAD)
  .set(TaskType.KYC_SELFIE_PICTURE_JOB, KYC_SELFIE_PICTURE_JOB)
  .set(TaskType.KYC_SELFIE_PICTURE_VERIFICATION, KYC_SELFIE_PICTURE_VERIFICATION)
  .set(TaskType.KYC_IDENTIFICATION_CARD_UPLOAD, KYC_IDENTIFICATION_CARD_UPLOAD)
  .set(TaskType.KYC_IDENTIFICATION_CARD_JOB, KYC_IDENTIFICATION_CARD_JOB)
  .set(TaskType.KYC_IDENTIFICATION_CARD_REVERSE_UPLOAD, KYC_IDENTIFICATION_CARD_REVERSE_UPLOAD)
  .set(TaskType.KYC_IDENTIFICATION_CARD_REVERSE_JOB, KYC_IDENTIFICATION_CARD_REVERSE_JOB)
  .set(TaskType.KYC_IDENTIFICATION_CARD_VERIFICATION, KYC_IDENTIFICATION_CARD_VERIFICATION)
  .set(TaskType.KYC_DRIVERS_LICENSE_UPLOAD, KYC_DRIVERS_LICENSE_UPLOAD)
  .set(TaskType.KYC_DRIVERS_LICENSE_JOB, KYC_DRIVERS_LICENSE_JOB)
  .set(TaskType.KYC_DRIVERS_LICENSE_REVERSE_UPLOAD, KYC_DRIVERS_LICENSE_REVERSE_UPLOAD)
  .set(TaskType.KYC_DRIVERS_LICENSE_REVERSE_JOB, KYC_DRIVERS_LICENSE_REVERSE_JOB)
  .set(TaskType.KYC_DRIVERS_LICENSE_VERIFICATION, KYC_DRIVERS_LICENSE_VERIFICATION)
  .set(TaskType.KYC_TAX_IDENTIFICATION_UPLOAD, KYC_TAX_IDENTIFICATION_UPLOAD)
  .set(TaskType.KYC_TAX_IDENTIFICATION_JOB, KYC_TAX_IDENTIFICATION_JOB)
  .set(TaskType.KYC_TAX_IDENTIFICATION_VERIFICATION, KYC_TAX_IDENTIFICATION_VERIFICATION)
  .set(TaskType.KYC_INACTIVITY_STATEMENT_UPLOAD, KYC_INACTIVITY_STATEMENT_UPLOAD)
  .set(TaskType.KYC_INACTIVITY_STATEMENT_JOB, KYC_INACTIVITY_STATEMENT_JOB)
  .set(TaskType.KYC_INACTIVITY_STATEMENT_VERIFICATION, KYC_INACTIVITY_STATEMENT_VERIFICATION)
  .set(TaskType.KYC_INCOME_STATEMENT_UPLOAD, KYC_INCOME_STATEMENT_UPLOAD)
  .set(TaskType.KYC_INCOME_STATEMENT_JOB, KYC_INCOME_STATEMENT_JOB)
  .set(TaskType.KYC_INCOME_STATEMENT_VERIFICATION, KYC_INCOME_STATEMENT_VERIFICATION)
  .set(TaskType.KYC_ADDRESS_INPUT, KYC_ADDRESS_INPUT)
  .set(TaskType.KYC_ADDRESS_PROOF_UPLOAD, KYC_ADDRESS_PROOF_UPLOAD)
  .set(TaskType.KYC_ADDRESS_PROOF_JOB, KYC_ADDRESS_PROOF_JOB)
  .set(TaskType.KYC_ADDRESS_VERIFICATION, KYC_ADDRESS_VERIFICATION)
  .set(TaskType.KYC_INACTIVITY_STATEMENT_INPUT, KYC_INACTIVITY_STATEMENT_INPUT)
  .set(TaskType.KYC_MEET_PICK_DATE, KYC_MEET_PICK_DATE)
  .set(TaskType.KYC_MEET_CONFIRM_DATE, KYC_MEET_CONFIRM_DATE)
  .set(TaskType.KYC_MEET_CANCEL_DATE, KYC_MEET_CANCEL_DATE)
  .set(TaskType.KYC_MEET_ADDRESS_MATCH, KYC_MEET_ADDRESS_MATCH)
  .set(TaskType.KYC_MEET_HOST_INVITATION, KYC_MEET_HOST_INVITATION)
  .set(TaskType.KYC_MEET_GUEST_INVITATION, KYC_MEET_GUEST_INVITATION)
  .set(TaskType.PAYMENT_CHECKOUT, PAYMENT_CHECKOUT)
  .set(TaskType.PAYMENT_RECONCILIATION, PAYMENT_RECONCILIATION)
  .set(TaskType.PAYMENT_VALIDATION, PAYMENT_VALIDATION)
  .set(TaskType.KYC_FINAL_APPROVAL, KYC_FINAL_APPROVAL)
  .set(TaskType.DELIVERY_DATE, DELIVERY_DATE)
  .set(TaskType.VEHICLE_INVENTORY_RESERVE, VEHICLE_INVENTORY_RESERVE)
  .set(TaskType.PENDING_DOCUMENTS, PENDING_DOCUMENTS)
  .set(TaskType.VEHICLE_INVENTORY_RELEASE, VEHICLE_INVENTORY_RELEASE)
  .set(TaskType.VEHICLE_TRACKER_INSTALLATION, VEHICLE_TRACKER_INSTALLATION)
  .set(TaskType.VEHICLE_TRACKER_SIM, VEHICLE_TRACKER_SIM)
  .set(TaskType.VEHICLE_TITLE, VEHICLE_TITLE)
  .set(TaskType.VEHICLE_AUTHORIZATION, VEHICLE_AUTHORIZATION)
  .set(TaskType.VEHICLE_ASSURANCE, VEHICLE_ASSURANCE)
  .set(TaskType.VEHICLE_STREET_TAG_INSTALLATION, VEHICLE_STREET_TAG_INSTALLATION)
  .set(TaskType.UBER_VEHICLE_REGISTRATION, UBER_VEHICLE_REGISTRATION)
  .set(TaskType.UBER_DRIVER_CONTRACT, UBER_DRIVER_CONTRACT)
  .set(TaskType.VEHICLE_HANDOFF_PICK_DATE, VEHICLE_HANDOFF_PICK_DATE)
  .set(TaskType.VEHICLE_HANDOFF_CONFIRM_DATE, VEHICLE_HANDOFF_CONFIRM_DATE)
  .set(TaskType.VEHICLE_HANDOFF_CANCEL_DATE, VEHICLE_HANDOFF_CANCEL_DATE)
  .set(TaskType.VEHICLE_HANDOFF_CHECKIN, VEHICLE_HANDOFF_CHECKIN)
  .set(TaskType.LEASING_CONTRACT_SIGNATURE, LEASING_CONTRACT_SIGNATURE)
