import { ValidationError } from '@domain/error/ValidationError'
import { ValueObject } from '@domain/kernel/ValueObject'

const values = {
  ONBOARD: 'ONBOARD',
  ONBOARD_BACKOFFICE_APPROVAL: 'ONBOARD_BACKOFFICE_APPROVAL',
  ONBOARD_MANAGER_APPROVAL: 'ONBOARD_MANAGER_APPROVAL',

  KYC_DRIVER_INPUT: 'KYC_DRIVER_INPUT',
  DRIVERS_LICENSE: 'DRIVERS_LICENSE',
  IDENTIFICATION_CARD: 'IDENTIFICATION_CARD',
  SELFIE_PICTURE: 'SELFIE_PICTURE',
  INACTIVITY_STATEMENT: 'INACTIVITY_STATEMENT',
  TAX_IDENTIFICATION: 'TAX_IDENTIFICATION',
  INCOME_STATEMENT: 'INCOME_STATEMENT',
  ADDRESS: 'ADDRESS',

  KYC_VERIFICATION: 'KYC_VERIFICATION',
  DRIVERS_LICENSE_VERIFICATION: 'DRIVERS_LICENSE_VERIFICATION',
  IDENTIFICATION_CARD_VERIFICATION: 'IDENTIFICATION_CARD_VERIFICATION',
  SELFIE_PICTURE_VERIFICATION: 'SELFIE_PICTURE_VERIFICATION',
  INACTIVITY_STATEMENT_VERIFICATION: 'INACTIVITY_STATEMENT_VERIFICATION',
  TAX_IDENTIFICATION_VERIFICATION: 'TAX_IDENTIFICATION_VERIFICATION',
  INCOME_STATEMENT_VERIFICATION: 'INCOME_STATEMENT_VERIFICATION',
  ADDRESS_VERIFICATION: 'ADDRESS_VERIFICATION',
  PAYMENT_CHECKOUT: 'PAYMENT_CHECKOUT',
  PAYMENT_RECONCILIATION: 'PAYMENT_RECONCILIATION',
  PAYMENT_VALIDATION: 'PAYMENT_VALIDATION',

  KYC_MEET_SCHEDULE: 'KYC_MEET_SCHEDULE',
  KYC_MEET_LIVE: 'KYC_MEET_LIVE',

  KYC_GOOD_TO_GO: 'KYC_GOOD_TO_GO',

  VEHICLE_SETUP: 'VEHICLE_SETUP',
  VEHICLE_INVENTORY: 'VEHICLE_INVENTORY',
  VEHICLE_TRACKER: 'VEHICLE_TRACKER',
  VEHICLE_DOCUMENTATION: 'VEHICLE_DOCUMENTATION',
  VEHICLE_STREET_TAG: 'VEHICLE_STREET_TAG',

  UBER_VEHICLE: 'UBER_VEHICLE',
  UBER_DRIVER: 'UBER_DRIVER',

  LEASING: 'LEASING',
  VEHICLE_HANDOFF: 'VEHICLE_HANDOFF',

  DELIVERY_DATE: 'DELIVERY_DATE',
}

export class ChecklistId extends ValueObject<'ChecklistId', string> {
  constructor(value: string) {
    const valid = Object.values(values)
    if (!valid.includes(value)) {
      throw new ValidationError(`Invalid Application ChecklistId [${value}], must be one of "${valid.join()}"`)
    }
    super(value)
  }

  static ONBOARD = new ChecklistId(values.ONBOARD)
  static ONBOARD_BACKOFFICE_APPROVAL = new ChecklistId(values.ONBOARD_BACKOFFICE_APPROVAL)
  static ONBOARD_MANAGER_APPROVAL = new ChecklistId(values.ONBOARD_MANAGER_APPROVAL)
  static KYC_DRIVER_INPUT = new ChecklistId(values.KYC_DRIVER_INPUT)
  static DRIVERS_LICENSE = new ChecklistId(values.DRIVERS_LICENSE)
  static IDENTIFICATION_CARD = new ChecklistId(values.IDENTIFICATION_CARD)
  static SELFIE_PICTURE = new ChecklistId(values.SELFIE_PICTURE)
  static INACTIVITY_STATEMENT = new ChecklistId(values.INACTIVITY_STATEMENT)
  static TAX_IDENTIFICATION = new ChecklistId(values.TAX_IDENTIFICATION)
  static INCOME_STATEMENT = new ChecklistId(values.INCOME_STATEMENT)
  static ADDRESS = new ChecklistId(values.ADDRESS)
  static KYC_VERIFICATION = new ChecklistId(values.KYC_VERIFICATION)
  static DRIVERS_LICENSE_VERIFICATION = new ChecklistId(values.DRIVERS_LICENSE_VERIFICATION)
  static IDENTIFICATION_CARD_VERIFICATION = new ChecklistId(values.IDENTIFICATION_CARD_VERIFICATION)

  static SELFIE_PICTURE_VERIFICATION = new ChecklistId(values.SELFIE_PICTURE_VERIFICATION)
  static INACTIVITY_STATEMENT_VERIFICATION = new ChecklistId(values.INACTIVITY_STATEMENT_VERIFICATION)
  static TAX_IDENTIFICATION_VERIFICATION = new ChecklistId(values.TAX_IDENTIFICATION_VERIFICATION)
  static INCOME_STATEMENT_VERIFICATION = new ChecklistId(values.INCOME_STATEMENT_VERIFICATION)
  static ADDRESS_VERIFICATION = new ChecklistId(values.ADDRESS_VERIFICATION)
  static PAYMENT_CHECKOUT = new ChecklistId(values.PAYMENT_CHECKOUT)
  static PAYMENT_RECONCILIATION = new ChecklistId(values.PAYMENT_RECONCILIATION)
  static PAYMENT_VALIDATION = new ChecklistId(values.PAYMENT_VALIDATION)

  static KYC_MEET_SCHEDULE = new ChecklistId(values.KYC_MEET_SCHEDULE)
  static KYC_MEET_LIVE = new ChecklistId(values.KYC_MEET_LIVE)
  static KYC_GOOD_TO_GO = new ChecklistId(values.KYC_GOOD_TO_GO)

  static VEHICLE_SETUP = new ChecklistId(values.VEHICLE_SETUP)
  static VEHICLE_INVENTORY = new ChecklistId(values.VEHICLE_INVENTORY)
  static VEHICLE_TRACKER = new ChecklistId(values.VEHICLE_TRACKER)
  static VEHICLE_DOCUMENTATION = new ChecklistId(values.VEHICLE_DOCUMENTATION)
  static VEHICLE_STREET_TAG = new ChecklistId(values.VEHICLE_STREET_TAG)

  static UBER_VEHICLE = new ChecklistId(values.UBER_VEHICLE)
  static UBER_DRIVER = new ChecklistId(values.UBER_DRIVER)

  static LEASING = new ChecklistId(values.LEASING)
  static VEHICLE_HANDOFF = new ChecklistId(values.VEHICLE_HANDOFF)

  static DELIVERY_DATE = new ChecklistId(values.DELIVERY_DATE)
}
