import { Collection } from '@domain/kernel/Collection'
import { ChecklistId } from './models/ChecklistId'
import { ChecklistConfig } from './interfaces/ChecklistConfig'
import { ADDRESS } from './implementations/ADDRESS'
import { DRIVERS_LICENSE } from './implementations/DRIVERS_LICENSE'
import { DRIVERS_LICENSE_VERIFICATION } from './implementations/DRIVERS_LICENSE_VERIFICATION'
import { IDENTIFICATION_CARD } from './implementations/IDENTIFICATION_CARD'
import { IDENTIFICATION_CARD_VERIFICATION } from './implementations/IDENTIFICATION_CARD_VERIFICATION'
import { INACTIVITY_STATEMENT } from './implementations/INACTIVITY_STATEMENT'
import { INACTIVITY_STATEMENT_VERIFICATION } from './implementations/INACTIVITY_STATEMENT_VERIFICATION'
import { INCOME_STATEMENT } from './implementations/INCOME_STATEMENT'
import { INCOME_STATEMENT_VERIFICATION } from './implementations/INCOME_STATEMENT_VERIFICATION'
import { KYC_GOOD_TO_GO } from './implementations/KYC_GOOD_TO_GO'
import { ONBOARD_BACKOFFICE_APPROVAL } from './implementations/ONBOARD_BACKOFFICE_APPROVAL'
import { ONBOARD_MANAGER_APPROVAL } from './implementations/ONBOARD_MANAGER_APPROVAL'
import { SELFIE_PICTURE } from './implementations/SELFIE_PICTURE'
import { SELFIE_PICTURE_VERIFICATION } from './implementations/SELFIE_PICTURE_VERIFICATION'
import { TAX_IDENTIFICATION } from './implementations/TAX_IDENTIFICATION'
import { TAX_IDENTIFICATION_VERIFICATION } from './implementations/TAX_IDENTIFICATION_VERIFICATION'
import { KYC_MEET_SCHEDULE } from './implementations/KYC_MEET_SCHEDULE'
import { ADDRESS_VERIFICATION } from './implementations/ADDRESS_VERIFICATION'
import { KYC_MEET_LIVE } from './implementations/KYC_MEET_LIVE'
import { UBER_DRIVER } from './implementations/UBER_DRIVER'
import { UBER_VEHICLE } from './implementations/UBER_VEHICLE'
import { VEHICLE_DOCUMENTATION } from './implementations/VEHICLE_DOCUMENTATION'
import { VEHICLE_HANDOFF } from './implementations/VEHICLE_HANDOFF'
import { VEHICLE_INVENTORY } from './implementations/VEHICLE_INVENTORY'
import { VEHICLE_STREET_TAG } from './implementations/VEHICLE_STREET_TAG'
import { VEHICLE_TRACKER } from './implementations/VEHICLE_TRACKER'

export const checklistCollection = new Collection<ChecklistConfig>()
  .set(ChecklistId.ONBOARD_BACKOFFICE_APPROVAL, ONBOARD_BACKOFFICE_APPROVAL)
  .set(ChecklistId.ONBOARD_MANAGER_APPROVAL, ONBOARD_MANAGER_APPROVAL)
  .set(ChecklistId.SELFIE_PICTURE, SELFIE_PICTURE)
  .set(ChecklistId.SELFIE_PICTURE_VERIFICATION, SELFIE_PICTURE_VERIFICATION)
  .set(ChecklistId.IDENTIFICATION_CARD, IDENTIFICATION_CARD)
  .set(ChecklistId.IDENTIFICATION_CARD_VERIFICATION, IDENTIFICATION_CARD_VERIFICATION)
  .set(ChecklistId.DRIVERS_LICENSE, DRIVERS_LICENSE)
  .set(ChecklistId.DRIVERS_LICENSE_VERIFICATION, DRIVERS_LICENSE_VERIFICATION)
  .set(ChecklistId.TAX_IDENTIFICATION, TAX_IDENTIFICATION)
  .set(ChecklistId.TAX_IDENTIFICATION_VERIFICATION, TAX_IDENTIFICATION_VERIFICATION)
  .set(ChecklistId.INCOME_STATEMENT, INCOME_STATEMENT)
  .set(ChecklistId.INCOME_STATEMENT_VERIFICATION, INCOME_STATEMENT_VERIFICATION)
  .set(ChecklistId.INACTIVITY_STATEMENT, INACTIVITY_STATEMENT)
  .set(ChecklistId.INACTIVITY_STATEMENT_VERIFICATION, INACTIVITY_STATEMENT_VERIFICATION)
  .set(ChecklistId.ADDRESS, ADDRESS)
  .set(ChecklistId.ADDRESS_VERIFICATION, ADDRESS_VERIFICATION)
  .set(ChecklistId.KYC_MEET_SCHEDULE, KYC_MEET_SCHEDULE)
  .set(ChecklistId.KYC_MEET_LIVE, KYC_MEET_LIVE)
  .set(ChecklistId.KYC_GOOD_TO_GO, KYC_GOOD_TO_GO)
  .set(ChecklistId.VEHICLE_INVENTORY, VEHICLE_INVENTORY)
  .set(ChecklistId.VEHICLE_TRACKER, VEHICLE_TRACKER)
  .set(ChecklistId.VEHICLE_DOCUMENTATION, VEHICLE_DOCUMENTATION)
  .set(ChecklistId.VEHICLE_STREET_TAG, VEHICLE_STREET_TAG)
  .set(ChecklistId.UBER_VEHICLE, UBER_VEHICLE)
  .set(ChecklistId.UBER_DRIVER, UBER_DRIVER)
  .set(ChecklistId.VEHICLE_HANDOFF, VEHICLE_HANDOFF)
