import { DTO } from '@domain/kernel/DTO'
import { ChecklistId } from './models/ChecklistId'
interface ChecklistDependencyMap {
  [key: DTO<ChecklistId>]: ChecklistId[]
}

const DEPENDENCIES: ChecklistDependencyMap = {
  SELFIE_PICTURE: [ChecklistId.ONBOARD_BACKOFFICE_APPROVAL, ChecklistId.ONBOARD_MANAGER_APPROVAL],
  IDENTIFICATION_CARD: [ChecklistId.ONBOARD_BACKOFFICE_APPROVAL, ChecklistId.ONBOARD_MANAGER_APPROVAL],
  DRIVERS_LICENSE: [ChecklistId.ONBOARD_BACKOFFICE_APPROVAL, ChecklistId.ONBOARD_MANAGER_APPROVAL],
  INCOME_STATEMENT: [ChecklistId.ONBOARD_BACKOFFICE_APPROVAL, ChecklistId.ONBOARD_MANAGER_APPROVAL],
  INACTIVITY_STATEMENT: [ChecklistId.ONBOARD_BACKOFFICE_APPROVAL, ChecklistId.ONBOARD_MANAGER_APPROVAL],
  TAX_IDENTIFICATION: [ChecklistId.ONBOARD_BACKOFFICE_APPROVAL, ChecklistId.ONBOARD_MANAGER_APPROVAL],
  ADDRESS: [ChecklistId.ONBOARD_BACKOFFICE_APPROVAL, ChecklistId.ONBOARD_MANAGER_APPROVAL],
  KYC_MEET_SCHEDULE: [ChecklistId.ONBOARD_BACKOFFICE_APPROVAL, ChecklistId.ONBOARD_MANAGER_APPROVAL],

  SELFIE_PICTURE_VERIFICATION: [ChecklistId.ADDRESS],
  DRIVERS_LICENSE_VERIFICATION: [ChecklistId.ADDRESS],
  IDENTIFICATION_CARD_VERIFICATION: [ChecklistId.ADDRESS],
  INCOME_STATEMENT_VERIFICATION: [ChecklistId.ADDRESS],
  TAX_IDENTIFICATION_VERIFICATION: [ChecklistId.ADDRESS],
  INACTIVITY_STATEMENT_VERIFICATION: [ChecklistId.ADDRESS],
  ADDRESS_VERIFICATION: [ChecklistId.ADDRESS],

  KYC_MEET_LIVE: [ChecklistId.KYC_MEET_SCHEDULE],

  KYC_GOOD_TO_GO: [ChecklistId.ONBOARD_BACKOFFICE_APPROVAL, ChecklistId.ONBOARD_MANAGER_APPROVAL],

  VEHICLE_INVENTORY: [ChecklistId.KYC_GOOD_TO_GO],
  VEHICLE_TRACKER: [ChecklistId.KYC_GOOD_TO_GO],
  VEHICLE_DOCUMENTATION: [ChecklistId.KYC_GOOD_TO_GO],
  VEHICLE_STREET_TAG: [ChecklistId.KYC_GOOD_TO_GO],

  DELIVERY_DATE: [ChecklistId.KYC_GOOD_TO_GO],
  PAYMENT_CHECKOUT: [ChecklistId.KYC_GOOD_TO_GO], 
  PAYMENT_RECONCILIATION: [ChecklistId.KYC_GOOD_TO_GO],
  PAYMENT_VALIDATION: [ChecklistId.KYC_GOOD_TO_GO],

  UBER_VEHICLE: [ChecklistId.VEHICLE_SETUP],
  UBER_DRIVER: [ChecklistId.VEHICLE_SETUP],

  VEHICLE_HANDOFF: [ChecklistId.VEHICLE_SETUP],
}
export class ChecklistDependencyService {
  static dependencies(checklistId: ChecklistId): ChecklistId[] {
    if (checklistId.toDTO() in DEPENDENCIES) {
      return DEPENDENCIES[checklistId.toDTO()]
    }

    return []
  }
}
