import { ValueObject } from '@domain/kernel/ValueObject'
import { ValidationError } from '@domain/error/ValidationError'

export const PROSPECT_ACTIVITY_TYPES = {
  PROSPECT_CREATED: 'PROSPECT_CREATED',
  QUOTE_CREATED: 'QUOTE_CREATED',

  USER_CONTACTED_CUSTOMER_SUPPORT: 'USER_CONTACTED_CUSTOMER_SUPPORT',
  CUSTOMER_SUPPORT_CONTACTED_USER: 'CUSTOMER_SUPPORT_CONTACTED_USER',
  CUSTOMER_SUPPORT_CLOSED: 'CUSTOMER_SUPPORT_CLOSED',

  APPLICATION_CREATED: 'APPLICATION_CREATED',

  APPLICATION_PREAPPROVAL_REQUESTED: 'APPLICATION_PREAPPROVAL_REQUESTED',
  APPLICATION_PREAPPROVAL_ACCEPTED: 'APPLICATION_PREAPPROVAL_ACCEPTED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  APPLICATION_EXPIRED: 'APPLICATION_EXPIRED',

  APPLICATION_KYC_USER_LOGGED_IN_APP: 'APPLICATION_KYC_USER_LOGGED_IN_APP',
  APPLICATION_KYC_APPROVED: 'APPLICATION_KYC_APPROVED',

  PROSPECT_REJECTED: 'PROSPECT_REJECTED',
  PROSPECT_ABANDONED: 'PROSPECT_ABANDONED',
  PROSPECT_CONVERTED: 'PROSPECT_CONVERTED',

  PROSPECT_STATUS_UPDATED: 'PROSPECT_STATUS_UPDATED',
  PROSPECT_SUPPORT_USER_ASSIGNED: 'PROSPECT_SUPPORT_USER_ASSIGNED',
  NOTE: 'NOTE',
}

export class ProspectActivityTypeId extends ValueObject<'ProspectActivityTypeId', string> {
  constructor(value: string) {
    const valid = Object.values(PROSPECT_ACTIVITY_TYPES)
    if (!valid.includes(value)) {
      throw new ValidationError(`Invalid ProspectActivityTypeId [${value}], must be one of "${valid.join()}"`)
    }
    super(value)
  }

  static get(value: ProspectActivityTypeId | string): ProspectActivityTypeId {
    return typeof value === 'string' ? new ProspectActivityTypeId(value) : value
  }

  static PROSPECT_CREATED = new ProspectActivityTypeId(PROSPECT_ACTIVITY_TYPES.PROSPECT_CREATED)
  static QUOTE_CREATED = new ProspectActivityTypeId(PROSPECT_ACTIVITY_TYPES.QUOTE_CREATED)

  static USER_CONTACTED_CUSTOMER_SUPPORT = new ProspectActivityTypeId(
    PROSPECT_ACTIVITY_TYPES.USER_CONTACTED_CUSTOMER_SUPPORT,
  )
  static CUSTOMER_SUPPORT_CONTACTED_USER = new ProspectActivityTypeId(
    PROSPECT_ACTIVITY_TYPES.CUSTOMER_SUPPORT_CONTACTED_USER,
  )
  static CUSTOMER_SUPPORT_CLOSED = new ProspectActivityTypeId(PROSPECT_ACTIVITY_TYPES.CUSTOMER_SUPPORT_CLOSED)

  static APPLICATION_CREATED = new ProspectActivityTypeId(PROSPECT_ACTIVITY_TYPES.APPLICATION_CREATED)

  static APPLICATION_PREAPPROVAL_REQUESTED = new ProspectActivityTypeId(
    PROSPECT_ACTIVITY_TYPES.APPLICATION_PREAPPROVAL_REQUESTED,
  )
  static APPLICATION_PREAPPROVAL_ACCEPTED = new ProspectActivityTypeId(
    PROSPECT_ACTIVITY_TYPES.APPLICATION_PREAPPROVAL_ACCEPTED,
  )
  static APPLICATION_REJECTED = new ProspectActivityTypeId(PROSPECT_ACTIVITY_TYPES.APPLICATION_REJECTED)
  static APPLICATION_EXPIRED = new ProspectActivityTypeId(PROSPECT_ACTIVITY_TYPES.APPLICATION_EXPIRED)

  static APPLICATION_KYC_USER_LOGGED_IN_APP = new ProspectActivityTypeId(
    PROSPECT_ACTIVITY_TYPES.APPLICATION_KYC_USER_LOGGED_IN_APP,
  )
  static APPLICATION_KYC_APPROVED = new ProspectActivityTypeId(PROSPECT_ACTIVITY_TYPES.APPLICATION_KYC_APPROVED)

  static PROSPECT_REJECTED = new ProspectActivityTypeId(PROSPECT_ACTIVITY_TYPES.PROSPECT_REJECTED)
  static PROSPECT_ABANDONED = new ProspectActivityTypeId(PROSPECT_ACTIVITY_TYPES.PROSPECT_ABANDONED)
  static PROSPECT_CONVERTED = new ProspectActivityTypeId(PROSPECT_ACTIVITY_TYPES.PROSPECT_CONVERTED)

  static PROSPECT_STATUS_UPDATED = new ProspectActivityTypeId(PROSPECT_ACTIVITY_TYPES.PROSPECT_STATUS_UPDATED)
  static PROSPECT_SUPPORT_USER_ASSIGNED = new ProspectActivityTypeId(
    PROSPECT_ACTIVITY_TYPES.PROSPECT_SUPPORT_USER_ASSIGNED,
  )
  static NOTE = new ProspectActivityTypeId(PROSPECT_ACTIVITY_TYPES.NOTE)
}
