apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: {{APP_NAME}}
  
resources:
  - ingress.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
- name: {{APP_NAME}}-config
  options:
    disableNameSuffixHash: true

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: webs
    unsetOnly: true