apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: web-autofinrent
  
resources:
  - web-autofinrent-ingress.yaml
  - web-autofinrent-deployment.yaml
  - web-autofinrent-service.yaml

configMapGenerator:
- name: web-autofinrent-config
  options:
    disableNameSuffixHash: true

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: autofinrent
    unsetOnly: true