apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-autofinrent
  name: web-autofinrent
  namespace: autofinrent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-autofinrent
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-autofinrent
    spec:
      containers:
        - image: {{image}}
          name: web-autofinrent
          ports:
            - name: web
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: web-autofinrent-config
      restartPolicy: Always
      imagePullSecrets:
        - name: dhsecret