apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${APP_NAME}
  name: ${APP_NAME}
  namespace: webs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${APP_NAME}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
        - image: {{image}}
          name: ${APP_NAME}
          ports:
            - name: web
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: ${APP_NAME}-config
      restartPolicy: Always
      imagePullSecrets:
        - name: dhsecret