apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: api-uber
  
resources:
  - uber-ingress.yaml
  - uber-deployment.yaml
  - uber-service.yaml

configMapGenerator:
- name: uber-config
  options:
    disableNameSuffixHash: true

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: uber
    unsetOnly: true