apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: kyc-service
  
resources:
  - kyc-ingress.yaml
  - kyc-deployment.yaml
  - kyc-service.yaml

configMapGenerator:
- name: kyc-service-config
  options:
    disableNameSuffixHash: true

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: kyc
    unsetOnly: true