apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-uber
  name: api-uber
  namespace: uber
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-uber
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-uber
    spec:
      containers:
        - image: {{image}}
          name: api-uber
          ports:
            - name: web
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: uber-config
      restartPolicy: Always
      imagePullSecrets:
        - name: dhsecret