import { Prisma } from '@prisma/client'

export const DATA_PRODUCTS: Prisma.ProductCreateInput[] = [
  {
    id: '36fe9006-d61d-4d8c-97c5-c30859b7e501',
    title: 'Nissan Versa 2019',
    brand: 'Nissan',
    model: 'Versa',
    series: 'Sense',
    defaultLeasingPeriod: 3,
    defaultWeeklyPrice: 2784,
    picture: 'https://web.test.divisionautomotriz.com/images/cars/versa-2019.png',
    estimatedAcceleration: 10.5,
    engineType: 'Combustión',
    estimatedHorsepower: 106,
    estimatedTopSpeedKmH: 175,
    numberOfSpeeds: 5,
    turbo: 'No',
    cylinders: '4',
    fuelType: 'Gasolina',
    liters: 1.6,
    estimatedTorqueLbFt: 105,
    startStop: 'No',
    frontElectricWindows: 'Sí',
    transmission: 'Manual',
    idversion: 7974,
  },
  {
    id: '9fdef98a-6994-4c49-bc44-445cfdabc30c',
    title: 'Chevrolet Aveo 2020',
    brand: 'Chevrolet',
    model: 'Aveo',
    series: 'LS',
    defaultLeasingPeriod: 3,
    defaultWeeklyPrice: 2703,
    picture: 'https://web.test.divisionautomotriz.com/images/cars/aveo-2020.png',
    estimatedAcceleration: 11.0,
    engineType: 'Combustión',
    estimatedHorsepower: 107,
    estimatedTopSpeedKmH: 170,
    numberOfSpeeds: 5,
    turbo: 'No',
    cylinders: '4L',
    fuelType: 'Gasolina',
    liters: 1.5,
    estimatedTorqueLbFt: 104,
    startStop: 'No',
    frontElectricWindows: 'Sí',
    transmission: 'Manual',
    idversion: 35370,
  },
]
