import { ValueObject } from '@domain/kernel/ValueObject'
import { ValidationError } from '@domain/error/ValidationError'

export const TASK_TYPES = {
  APPLICATION_BACKOFFICE_APPROVAL: 'APPLICATION_BACKOFFICE_APPROVAL',
  APPLICATION_MANAGER_APPROVAL: 'APPLICATION_MANAGER_APPROVAL',

  KYC_ADDRESS_INPUT: 'KYC_ADDRESS_INPUT',
  KYC_ADDRESS_PROOF_UPLOAD: 'KYC_ADDRESS_PROOF_UPLOAD',
  KYC_INACTIVITY_STATEMENT_INPUT: 'KYC_INACTIVITY_STATEMENT_INPUT',
  KYC_SELFIE_PICTURE_UPLOAD: 'KYC_SELFIE_PICTURE_UPLOAD',
  KYC_DRIVERS_LICENSE_UPLOAD: 'KYC_DRIVERS_LICENSE_UPLOAD',
  KYC_DRIVERS_LICENSE_REVERSE_UPLOAD: 'KYC_DRIVERS_LICENSE_REVERSE_UPLOAD',
  KYC_IDENTIFICATION_CARD_UPLOAD: 'KYC_IDENTIFICATION_CARD_UPLOAD',
  KYC_IDENTIFICATION_CARD_REVERSE_UPLOAD: 'KYC_IDENTIFICATION_CARD_REVERSE_UPLOAD',
  KYC_INCOME_STATEMENT_UPLOAD: 'KYC_INCOME_STATEMENT_UPLOAD',
  KYC_INACTIVITY_STATEMENT_UPLOAD: 'KYC_INACTIVITY_STATEMENT_UPLOAD',
  KYC_TAX_IDENTIFICATION_UPLOAD: 'KYC_TAX_IDENTIFICATION_UPLOAD',

  KYC_ADDRESS_PROOF_JOB: 'KYC_ADDRESS_PROOF_JOB',
  KYC_SELFIE_PICTURE_JOB: 'KYC_SELFIE_PICTURE_JOB',
  KYC_DRIVERS_LICENSE_JOB: 'KYC_DRIVERS_LICENSE_JOB',
  KYC_DRIVERS_LICENSE_REVERSE_JOB: 'KYC_DRIVERS_LICENSE_REVERSE_JOB',
  KYC_IDENTIFICATION_CARD_JOB: 'KYC_IDENTIFICATION_CARD_JOB',
  KYC_IDENTIFICATION_CARD_REVERSE_JOB: 'KYC_IDENTIFICATION_CARD_REVERSE_JOB',
  KYC_INCOME_STATEMENT_JOB: 'KYC_INCOME_STATEMENT_JOB',
  KYC_INACTIVITY_STATEMENT_JOB: 'KYC_INACTIVITY_STATEMENT_JOB',
  KYC_TAX_IDENTIFICATION_JOB: 'KYC_TAX_IDENTIFICATION_JOB',

  KYC_ADDRESS_VERIFICATION: 'KYC_ADDRESS_VERIFICATION',
  KYC_SELFIE_PICTURE_VERIFICATION: 'KYC_SELFIE_PICTURE_VERIFICATION',
  KYC_DRIVERS_LICENSE_VERIFICATION: 'KYC_DRIVERS_LICENSE_VERIFICATION',
  KYC_IDENTIFICATION_CARD_VERIFICATION: 'KYC_IDENTIFICATION_CARD_VERIFICATION',
  KYC_INCOME_STATEMENT_VERIFICATION: 'KYC_INCOME_STATEMENT_VERIFICATION',
  KYC_INACTIVITY_STATEMENT_VERIFICATION: 'KYC_INACTIVITY_STATEMENT_VERIFICATION',
  KYC_TAX_IDENTIFICATION_VERIFICATION: 'KYC_TAX_IDENTIFICATION_VERIFICATION',

  KYC_MEET_PICK_DATE: 'KYC_MEET_PICK_DATE',
  KYC_MEET_CONFIRM_DATE: 'KYC_MEET_CONFIRM_DATE',
  KYC_MEET_CANCEL_DATE: 'KYC_MEET_CANCEL_DATE',
  KYC_MEET_CHECKIN: 'KYC_MEET_CHECKIN',
  KYC_MEET_HOST_INVITATION: 'KYC_MEET_HOST_INVITATION',
  KYC_MEET_GUEST_INVITATION: 'KYC_MEET_GUEST_INVITATION',
  KYC_MEET_ADDRESS_MATCH: 'KYC_MEET_ADDRESS_MATCH',

  PAYMENT_CHECKOUT: 'PAYMENT_CHECKOUT',
  PAYMENT_RECONCILIATION: 'PAYMENT_RECONCILIATION',
  PAYMENT_VALIDATION: 'PAYMENT_VALIDATION',
  KYC_FINAL_APPROVAL: 'KYC_FINAL_APPROVAL',
  DELIVERY_DATE: 'DELIVERY_DATE',

  PENDING_DOCUMENTS: 'PENDING_DOCUMENTS',
  VEHICLE_INVENTORY_RESERVE: 'VEHICLE_INVENTORY_RESERVE',
  VEHICLE_INVENTORY_RELEASE: 'VEHICLE_INVENTORY_RELEASE',

  VEHICLE_TRACKER_INSTALLATION: 'VEHICLE_TRACKER_INSTALLATION',
  VEHICLE_TRACKER_SIM: 'VEHICLE_TRACKER_SIM',

  VEHICLE_TITLE: 'VEHICLE_TITLE',
  VEHICLE_AUTHORIZATION: 'VEHICLE_AUTHORIZATION',
  VEHICLE_ASSURANCE: 'VEHICLE_ASSURANCE',

  VEHICLE_STREET_TAG_INSTALLATION: 'VEHICLE_STREET_TAG_INSTALLATION',

  UBER_VEHICLE_REGISTRATION: 'UBER_VEHICLE_REGISTRATION',

  UBER_DRIVER_CONTRACT: 'UBER_DRIVER_CONTRACT',

  VEHICLE_HANDOFF_PICK_DATE: 'VEHICLE_HANDOFF_PICK_DATE',
  VEHICLE_HANDOFF_CONFIRM_DATE: 'VEHICLE_HANDOFF_CONFIRM_DATE',
  VEHICLE_HANDOFF_CANCEL_DATE: 'VEHICLE_HANDOFF_CANCEL_DATE',
  VEHICLE_HANDOFF_CHECKIN: 'VEHICLE_HANDOFF_CHECKIN',
  LEASING_CONTRACT_SIGNATURE: 'LEASING_CONTRACT_SIGNATURE',
}

export class TaskType extends ValueObject<'TaskType', string> {
  constructor(value: string) {
    const valid = Object.values(TASK_TYPES)
    if (!valid.includes(value)) {
      throw new ValidationError(`Invalid TaskType [${value}], must be one of "${valid.join()}"`)
    }
    super(value)
  }

  static get(value: TaskType | string): TaskType {
    return typeof value === 'string' ? new TaskType(value) : value
  }

  static APPLICATION_BACKOFFICE_APPROVAL = new TaskType(TASK_TYPES.APPLICATION_BACKOFFICE_APPROVAL)
  static APPLICATION_MANAGER_APPROVAL = new TaskType(TASK_TYPES.APPLICATION_MANAGER_APPROVAL)

  static KYC_SELFIE_PICTURE_UPLOAD = new TaskType(TASK_TYPES.KYC_SELFIE_PICTURE_UPLOAD)
  static KYC_SELFIE_PICTURE_JOB = new TaskType(TASK_TYPES.KYC_SELFIE_PICTURE_JOB)
  static KYC_SELFIE_PICTURE_VERIFICATION = new TaskType(TASK_TYPES.KYC_SELFIE_PICTURE_VERIFICATION)

  static KYC_DRIVERS_LICENSE_UPLOAD = new TaskType(TASK_TYPES.KYC_DRIVERS_LICENSE_UPLOAD)
  static KYC_DRIVERS_LICENSE_JOB = new TaskType(TASK_TYPES.KYC_DRIVERS_LICENSE_JOB)
  static KYC_DRIVERS_LICENSE_REVERSE_UPLOAD = new TaskType(TASK_TYPES.KYC_DRIVERS_LICENSE_REVERSE_UPLOAD)
  static KYC_DRIVERS_LICENSE_REVERSE_JOB = new TaskType(TASK_TYPES.KYC_DRIVERS_LICENSE_REVERSE_JOB)
  static KYC_DRIVERS_LICENSE_VERIFICATION = new TaskType(TASK_TYPES.KYC_DRIVERS_LICENSE_VERIFICATION)

  static KYC_IDENTIFICATION_CARD_UPLOAD = new TaskType(TASK_TYPES.KYC_IDENTIFICATION_CARD_UPLOAD)
  static KYC_IDENTIFICATION_CARD_JOB = new TaskType(TASK_TYPES.KYC_IDENTIFICATION_CARD_JOB)
  static KYC_IDENTIFICATION_CARD_REVERSE_UPLOAD = new TaskType(TASK_TYPES.KYC_IDENTIFICATION_CARD_REVERSE_UPLOAD)
  static KYC_IDENTIFICATION_CARD_REVERSE_JOB = new TaskType(TASK_TYPES.KYC_IDENTIFICATION_CARD_REVERSE_JOB)
  static KYC_IDENTIFICATION_CARD_VERIFICATION = new TaskType(TASK_TYPES.KYC_IDENTIFICATION_CARD_VERIFICATION)

  static KYC_INCOME_STATEMENT_UPLOAD = new TaskType(TASK_TYPES.KYC_INCOME_STATEMENT_UPLOAD)
  static KYC_INCOME_STATEMENT_JOB = new TaskType(TASK_TYPES.KYC_INCOME_STATEMENT_JOB)
  static KYC_INCOME_STATEMENT_VERIFICATION = new TaskType(TASK_TYPES.KYC_INCOME_STATEMENT_VERIFICATION)

  static KYC_INACTIVITY_STATEMENT_UPLOAD = new TaskType(TASK_TYPES.KYC_INACTIVITY_STATEMENT_UPLOAD)
  static KYC_INACTIVITY_STATEMENT_JOB = new TaskType(TASK_TYPES.KYC_INACTIVITY_STATEMENT_JOB)
  static KYC_INACTIVITY_STATEMENT_VERIFICATION = new TaskType(TASK_TYPES.KYC_INACTIVITY_STATEMENT_VERIFICATION)

  static KYC_TAX_IDENTIFICATION_UPLOAD = new TaskType(TASK_TYPES.KYC_TAX_IDENTIFICATION_UPLOAD)
  static KYC_TAX_IDENTIFICATION_JOB = new TaskType(TASK_TYPES.KYC_TAX_IDENTIFICATION_JOB)
  static KYC_TAX_IDENTIFICATION_VERIFICATION = new TaskType(TASK_TYPES.KYC_TAX_IDENTIFICATION_VERIFICATION)

  static KYC_INACTIVITY_STATEMENT_INPUT = new TaskType(TASK_TYPES.KYC_INACTIVITY_STATEMENT_INPUT)

  static KYC_ADDRESS_INPUT = new TaskType(TASK_TYPES.KYC_ADDRESS_INPUT)
  static KYC_ADDRESS_PROOF_UPLOAD = new TaskType(TASK_TYPES.KYC_ADDRESS_PROOF_UPLOAD)
  static KYC_ADDRESS_PROOF_JOB = new TaskType(TASK_TYPES.KYC_ADDRESS_PROOF_JOB)
  static KYC_ADDRESS_VERIFICATION = new TaskType(TASK_TYPES.KYC_ADDRESS_VERIFICATION)

  static KYC_MEET_PICK_DATE = new TaskType(TASK_TYPES.KYC_MEET_PICK_DATE)
  static KYC_MEET_CONFIRM_DATE = new TaskType(TASK_TYPES.KYC_MEET_CONFIRM_DATE)
  static KYC_MEET_CANCEL_DATE = new TaskType(TASK_TYPES.KYC_MEET_CANCEL_DATE)
  static KYC_MEET_HOST_INVITATION = new TaskType(TASK_TYPES.KYC_MEET_HOST_INVITATION)
  static KYC_MEET_GUEST_INVITATION = new TaskType(TASK_TYPES.KYC_MEET_GUEST_INVITATION)
  static KYC_MEET_CHECKIN = new TaskType(TASK_TYPES.KYC_MEET_CHECKIN)
  static KYC_MEET_ADDRESS_MATCH = new TaskType(TASK_TYPES.KYC_MEET_ADDRESS_MATCH)

  static PAYMENT_CHECKOUT = new TaskType(TASK_TYPES.PAYMENT_CHECKOUT)
  static PAYMENT_RECONCILIATION = new TaskType(TASK_TYPES.PAYMENT_RECONCILIATION)
  static PAYMENT_VALIDATION = new TaskType(TASK_TYPES.PAYMENT_VALIDATION)
  static KYC_FINAL_APPROVAL = new TaskType(TASK_TYPES.KYC_FINAL_APPROVAL)
  static DELIVERY_DATE = new TaskType(TASK_TYPES.DELIVERY_DATE)

  static PENDING_DOCUMENTS = new TaskType(TASK_TYPES.PENDING_DOCUMENTS)
  static VEHICLE_INVENTORY_RESERVE = new TaskType(TASK_TYPES.VEHICLE_INVENTORY_RESERVE)
  static VEHICLE_INVENTORY_RELEASE = new TaskType(TASK_TYPES.VEHICLE_INVENTORY_RELEASE)

  static VEHICLE_TRACKER_INSTALLATION = new TaskType(TASK_TYPES.VEHICLE_TRACKER_INSTALLATION)
  static VEHICLE_TRACKER_SIM = new TaskType(TASK_TYPES.VEHICLE_TRACKER_SIM)

  static VEHICLE_TITLE = new TaskType(TASK_TYPES.VEHICLE_TITLE)
  static VEHICLE_AUTHORIZATION = new TaskType(TASK_TYPES.VEHICLE_AUTHORIZATION)
  static VEHICLE_ASSURANCE = new TaskType(TASK_TYPES.VEHICLE_ASSURANCE)

  static VEHICLE_STREET_TAG_INSTALLATION = new TaskType(TASK_TYPES.VEHICLE_STREET_TAG_INSTALLATION)

  static UBER_VEHICLE_REGISTRATION = new TaskType(TASK_TYPES.UBER_VEHICLE_REGISTRATION)

  static UBER_DRIVER_CONTRACT = new TaskType(TASK_TYPES.UBER_DRIVER_CONTRACT)

  static VEHICLE_HANDOFF_PICK_DATE = new TaskType(TASK_TYPES.VEHICLE_HANDOFF_PICK_DATE)
  static VEHICLE_HANDOFF_CONFIRM_DATE = new TaskType(TASK_TYPES.VEHICLE_HANDOFF_CONFIRM_DATE)
  static VEHICLE_HANDOFF_CANCEL_DATE = new TaskType(TASK_TYPES.VEHICLE_HANDOFF_CANCEL_DATE)
  static VEHICLE_HANDOFF_CHECKIN = new TaskType(TASK_TYPES.VEHICLE_HANDOFF_CHECKIN)
  static LEASING_CONTRACT_SIGNATURE = new TaskType(TASK_TYPES.LEASING_CONTRACT_SIGNATURE)
}
